// Script: generar_43_api_enviar_recordatorios.js
// Que hace: crea la API que efectivamente revisa la hora y manda las
// notificaciones push de recordatorio.
//
//   1) app/api/cron/recordatorios/route.ts (ARCHIVO NUEVO) -- esta ruta
//      sera llamada UNA VEZ POR HORA por un servicio externo (cron-job.org,
//      que configuraremos en la siguiente entrega). Cada vez que se
//      ejecuta: calcula la hora actual en Chile, busca los usuarios que
//      eligieron justo esa hora como su recordatorio, y para cada uno
//      revisa cada una de sus mascotas -- si no tiene registro de HOY,
//      le manda una notificacion separada (una por mascota sin
//      registrar, como se definio). Si una suscripcion ya no es valida
//      (el usuario desinstalo o revoco el permiso), se borra sola de
//      la base de datos.
//
//      Esta ruta esta protegida con CRON_SECRET (ya configurado en
//      Vercel) -- solo se ejecuta si quien la llama manda el secreto
//      correcto en el header Authorization, para que nadie mas pueda
//      activarla y mandar notificaciones falsas.
//
// IMPORTANTE -- paso adicional antes de correr este script:
// Este codigo necesita el paquete "web-push" instalado en el proyecto.
// Antes de correr el script de abajo, abre CMD en la raiz del proyecto
// y corre:
//
//   npm install web-push
//
// Esto va a actualizar tu package.json y package-lock.json
// automaticamente (instala el paquete real, agrega la dependencia).
// Una vez que eso termine sin errores, recien ahi corre este script.
//
// Como correrlo: node generar_43_api_enviar_recordatorios.js
// Confirma "OK: app/api/cron/recordatorios/route.ts"

const fs = require('fs');
const path = require('path');

const filePath = path.join('app', 'api', 'cron', 'recordatorios', 'route.ts');
const b64 = "aW1wb3J0IHsgTmV4dFJlc3BvbnNlIH0gZnJvbSAnbmV4dC9zZXJ2ZXInCmltcG9ydCB3ZWJwdXNoIGZyb20gJ3dlYi1wdXNoJwppbXBvcnQgeyBjcmVhdGVDbGllbnQgfSBmcm9tICdAc3VwYWJhc2Uvc3VwYWJhc2UtanMnCgovLyBFc3RhIHJ1dGEgbGEgbGxhbWEgdW4gc2VydmljaW8gZXh0ZXJubyAoY3Jvbi1qb2Iub3JnKSBVTkEgVkVaIFBPUiBIT1JBLAovLyBlbiBwdW50by4gQ2FkYSB2ZXogcXVlIHNlIGVqZWN1dGE6Ci8vICAgMS4gQ2FsY3VsYSBsYSBob3JhIGFjdHVhbCBlbiBDaGlsZSAoQW1lcmljYS9TYW50aWFnbykuCi8vICAgMi4gQnVzY2EgbG9zIHVzdWFyaW9zIHF1ZSBhY3RpdmFyb24gbm90aWZpY2FjaW9uZXMgeSBlbGlnaWVyb24KLy8gICAgICBqdXN0byBlc2EgaG9yYSBjb21vIHN1IHJlY29yZGF0b3Jpby4KLy8gICAzLiBQYXJhIGNhZGEgdW5vLCByZXZpc2EgY2FkYSB1bmEgZGUgc3VzIG1hc2NvdGFzOiBzaSBubyB0aWVuZQovLyAgICAgIHJlZ2lzdHJvIGRlIEhPWSwgbGUgbWFuZGEgdW5hIG5vdGlmaWNhY2lvbiBzZXBhcmFkYSBwb3IgbWFzY290YQovLyAgICAgIChubyB1bmEgc29sYSBhZ3J1cGFkYSAtLSBhc2kgc2UgZGVmaW5pbykuCi8vICAgNC4gU2kgdW5hIG1hc2NvdGEgeWEgdGllbmUgcmVnaXN0cm8gaG95LCBubyBzZSBsZSBtYW5kYSBuYWRhIChubwovLyAgICAgIHRpZW5lIHNlbnRpZG8gcmVjb3JkYXJsZSBhbGdvIHF1ZSB5YSBoaXpvKS4KLy8KLy8gUHJvdGVnaWRhIGNvbiBDUk9OX1NFQ1JFVCBwYXJhIHF1ZSBzb2xvIGVsIHNlcnZpY2lvIGRlIGNyb24gYXV0b3JpemFkbwovLyBwdWVkYSBhY3RpdmFybGEgLS0gc2luIGVzdG8sIGN1YWxxdWllcmEgcG9kcmlhIGxsYW1hciBlc3RhIFVSTCB5Ci8vIGhhY2VyIHF1ZSBzZSBtYW5kZW4gbm90aWZpY2FjaW9uZXMgZmFsc2FzIGEgbG9zIHVzdWFyaW9zLgoKZnVuY3Rpb24gY3JlYXJDbGllbnRlQWRtaW4oKSB7CiAgcmV0dXJuIGNyZWF0ZUNsaWVudCgKICAgIHByb2Nlc3MuZW52Lk5FWFRfUFVCTElDX1NVUEFCQVNFX1VSTCEsCiAgICBwcm9jZXNzLmVudi5TVVBBQkFTRV9TRVJWSUNFX1JPTEVfS0VZIQogICkKfQoKZnVuY3Rpb24gaG9yYUFjdHVhbENoaWxlKCk6IHN0cmluZyB7CiAgY29uc3QgYWhvcmEgPSBuZXcgRGF0ZSgpCiAgY29uc3QgaG9yYUNoaWxlID0gbmV3IEludGwuRGF0ZVRpbWVGb3JtYXQoJ2VzLUNMJywgewogICAgdGltZVpvbmU6ICdBbWVyaWNhL1NhbnRpYWdvJywKICAgIGhvdXI6ICcyLWRpZ2l0JywKICAgIGhvdXIxMjogZmFsc2UsCiAgfSkuZm9ybWF0KGFob3JhKQogIC8vIEVsIGZvcm1hdG8gcHVlZGUgZGV2b2x2ZXIgIjIwIiBvICIyMDowMCIgc2VndW4gZWwgbmF2ZWdhZG9yL3J1bnRpbWU7CiAgLy8gbm9ybWFsaXphbW9zIHNpZW1wcmUgYSAiSEg6MDAiIHBvcnF1ZSBsb3MgaG9yYXJpb3MgZGlzcG9uaWJsZXMgc29uCiAgLy8gZW4gcHVudG8uCiAgY29uc3QgaG9yYSA9IGhvcmFDaGlsZS5yZXBsYWNlKC9bXjAtOV0vZywgJycpLnBhZFN0YXJ0KDIsICcwJykuc2xpY2UoMCwgMikKICByZXR1cm4gYCR7aG9yYX06MDBgCn0KCmZ1bmN0aW9uIGZlY2hhSG95Q2hpbGUoKTogc3RyaW5nIHsKICBjb25zdCBhaG9yYSA9IG5ldyBEYXRlKCkKICByZXR1cm4gbmV3IEludGwuRGF0ZVRpbWVGb3JtYXQoJ2VuLUNBJywgeyB0aW1lWm9uZTogJ0FtZXJpY2EvU2FudGlhZ28nIH0pLmZvcm1hdChhaG9yYSkKfQoKZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEdFVChyZXF1ZXN0OiBSZXF1ZXN0KSB7CiAgY29uc3QgYXV0aEhlYWRlciA9IHJlcXVlc3QuaGVhZGVycy5nZXQoJ2F1dGhvcml6YXRpb24nKQogIGlmIChhdXRoSGVhZGVyICE9PSBgQmVhcmVyICR7cHJvY2Vzcy5lbnYuQ1JPTl9TRUNSRVR9YCkgewogICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgZXJyb3I6ICdObyBhdXRvcml6YWRvJyB9LCB7IHN0YXR1czogNDAxIH0pCiAgfQoKICB3ZWJwdXNoLnNldFZhcGlkRGV0YWlscygKICAgICdtYWlsdG86Y29udGFjdG9AY2hpcXVpLWFwcC5jbCcsCiAgICBwcm9jZXNzLmVudi5ORVhUX1BVQkxJQ19WQVBJRF9QVUJMSUNfS0VZISwKICAgIHByb2Nlc3MuZW52LlZBUElEX1BSSVZBVEVfS0VZIQogICkKCiAgY29uc3Qgc3VwYWJhc2UgPSBjcmVhckNsaWVudGVBZG1pbigpCiAgY29uc3QgaG9yYUFjdHVhbCA9IGhvcmFBY3R1YWxDaGlsZSgpCiAgY29uc3QgaG95ID0gZmVjaGFIb3lDaGlsZSgpCgogIC8vIFBhc28gMTogdXN1YXJpb3MgY29uIHJlY29yZGF0b3JpbyBhY3Rpdm8ganVzdG8gYSBlc3RhIGhvcmEuCiAgY29uc3QgeyBkYXRhOiB1c3VhcmlvcyB9ID0gYXdhaXQgc3VwYWJhc2UKICAgIC5mcm9tKCdwcmVmZXJlbmNpYXNfdXN1YXJpbycpCiAgICAuc2VsZWN0KCd1c2VyX2lkJykKICAgIC5lcSgnbm90aWZpY2FjaW9uZXNfYWN0aXZhcycsIHRydWUpCiAgICAuZXEoJ2hvcmFfcmVjb3JkYXRvcmlvJywgaG9yYUFjdHVhbCkKCiAgaWYgKCF1c3VhcmlvcyB8fCB1c3Vhcmlvcy5sZW5ndGggPT09IDApIHsKICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNvbih7IG1lbnNhamU6ICdTaW4gdXN1YXJpb3MgcGFyYSBlc3RhIGhvcmEnLCBob3JhOiBob3JhQWN0dWFsLCBlbnZpYWRvczogMCB9KQogIH0KCiAgbGV0IHRvdGFsRW52aWFkb3MgPSAwCiAgbGV0IHRvdGFsRXJyb3JlcyA9IDAKCiAgZm9yIChjb25zdCB1IG9mIHVzdWFyaW9zKSB7CiAgICAvLyBQYXNvIDI6IG1hc2NvdGFzIGRlIGVzdGUgdXN1YXJpby4KICAgIGNvbnN0IHsgZGF0YTogbWFzY290YXMgfSA9IGF3YWl0IHN1cGFiYXNlCiAgICAgIC5mcm9tKCdtYXNjb3RhcycpCiAgICAgIC5zZWxlY3QoJ2lkLCBub21icmUnKQogICAgICAuZXEoJ3VzZXJfaWQnLCB1LnVzZXJfaWQpCgogICAgaWYgKCFtYXNjb3RhcyB8fCBtYXNjb3Rhcy5sZW5ndGggPT09IDApIGNvbnRpbnVlCgogICAgLy8gUGFzbyAzOiBzdXNjcmlwY2lvbmVzIHB1c2ggZGUgZXN0ZSB1c3VhcmlvIChwdWVkZSB0ZW5lciBtYXMgZGUKICAgIC8vIHVuYSBzaSBpbnN0YWxvIGVuIHZhcmlvcyBkaXNwb3NpdGl2b3MpLgogICAgY29uc3QgeyBkYXRhOiBzdXNjcmlwY2lvbmVzIH0gPSBhd2FpdCBzdXBhYmFzZQogICAgICAuZnJvbSgnc3VzY3JpcGNpb25lc19wdXNoJykKICAgICAgLnNlbGVjdCgnaWQsIGVuZHBvaW50LCBwMjU2ZGgsIGF1dGgnKQogICAgICAuZXEoJ3VzZXJfaWQnLCB1LnVzZXJfaWQpCgogICAgaWYgKCFzdXNjcmlwY2lvbmVzIHx8IHN1c2NyaXBjaW9uZXMubGVuZ3RoID09PSAwKSBjb250aW51ZQoKICAgIGZvciAoY29uc3QgbWFzY290YSBvZiBtYXNjb3RhcykgewogICAgICAvLyBQYXNvIDQ6IHJldmlzYXIgc2kgZXN0YSBtYXNjb3RhIHlhIHRpZW5lIHJlZ2lzdHJvIGhveS4KICAgICAgY29uc3QgeyBkYXRhOiByZWdpc3Ryb0hveSB9ID0gYXdhaXQgc3VwYWJhc2UKICAgICAgICAuZnJvbSgncmVnaXN0cm9zX2RpYXJpb3MnKQogICAgICAgIC5zZWxlY3QoJ2lkJykKICAgICAgICAuZXEoJ21hc2NvdGFfaWQnLCBtYXNjb3RhLmlkKQogICAgICAgIC5lcSgnZmVjaGEnLCBob3kpCiAgICAgICAgLm1heWJlU2luZ2xlKCkKCiAgICAgIGlmIChyZWdpc3Ryb0hveSkgY29udGludWUgLy8geWEgcmVnaXN0cm8gaG95LCBubyBzZSBsZSBtYW5kYSBuYWRhCgogICAgICBjb25zdCBwYXlsb2FkID0gSlNPTi5zdHJpbmdpZnkoewogICAgICAgIHRpdGxlOiAnQ0hJUVVJIEVudHJlIFNlw7FhbGVzJywKICAgICAgICBib2R5OiBgwr9Dw7NtbyBlc3R1dm8gJHttYXNjb3RhLm5vbWJyZX0gaG95PyBBw7puIG5vIGxvIGhhcyByZWdpc3RyYWRvLmAsCiAgICAgICAgdXJsOiAnL3JlZ2lzdHJvLWRpYXJpbycsCiAgICAgIH0pCgogICAgICBmb3IgKGNvbnN0IHN1YiBvZiBzdXNjcmlwY2lvbmVzKSB7CiAgICAgICAgdHJ5IHsKICAgICAgICAgIGF3YWl0IHdlYnB1c2guc2VuZE5vdGlmaWNhdGlvbigKICAgICAgICAgICAgeyBlbmRwb2ludDogc3ViLmVuZHBvaW50LCBrZXlzOiB7IHAyNTZkaDogc3ViLnAyNTZkaCwgYXV0aDogc3ViLmF1dGggfSB9LAogICAgICAgICAgICBwYXlsb2FkCiAgICAgICAgICApCiAgICAgICAgICB0b3RhbEVudmlhZG9zKysKICAgICAgICB9IGNhdGNoIChlcnI6IGFueSkgewogICAgICAgICAgdG90YWxFcnJvcmVzKysKICAgICAgICAgIC8vIFNpIGxhIHN1c2NyaXBjaW9uIHlhIG5vIGVzIHZhbGlkYSAoZWouIGVsIHVzdWFyaW8gZGVzaW5zdGFsbwogICAgICAgICAgLy8gbGEgYXBwIG8gcmV2b2NvIGVsIHBlcm1pc28gZGVzZGUgZWwgbmF2ZWdhZG9yKSwgbGEgbGltcGlhbW9zCiAgICAgICAgICAvLyBkZSBsYSBiYXNlIGRlIGRhdG9zIHBhcmEgbm8gc2VndWlyIGludGVudGFuZG8gZW4gdmFuby4KICAgICAgICAgIGlmIChlcnIuc3RhdHVzQ29kZSA9PT0gNDA0IHx8IGVyci5zdGF0dXNDb2RlID09PSA0MTApIHsKICAgICAgICAgICAgYXdhaXQgc3VwYWJhc2UuZnJvbSgnc3VzY3JpcGNpb25lc19wdXNoJykuZGVsZXRlKCkuZXEoJ2lkJywgc3ViLmlkKQogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfQogICAgfQogIH0KCiAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgaG9yYTogaG9yYUFjdHVhbCwgdXN1YXJpb3M6IHVzdWFyaW9zLmxlbmd0aCwgZW52aWFkb3M6IHRvdGFsRW52aWFkb3MsIGVycm9yZXM6IHRvdGFsRXJyb3JlcyB9KQp9Cg==";
const content = Buffer.from(b64, 'base64').toString('utf8');

const dir = path.dirname(filePath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

fs.writeFileSync(filePath, content, 'utf8');
console.log('OK: ' + filePath);
