const fs = require('fs');
const path = require('path');

// ============================================================
// generar_457_chiqui_flotante.js
// ============================================================
// El chat pasa a estar disponible EN CUALQUIER PANTALLA, no solo en
// Analisis.
//
// COMO SE VE
// Una burbuja fija abajo a la derecha, sobre la barra de navegacion.
// Aparece 2,5 segundos despues de entrar —no de inmediato, para no
// competir con lo que la persona vino a hacer— y saluda con un globito:
//
//   Soy Chiqui, ¿hablamos?
//
// El globito se retira solo a los 9 segundos. Si nadie lo toca, deja de
// estorbar.
//
// DONDE NO APARECE
//   - Analisis: ahi ya esta como tarjeta dentro del contenido.
//   - Registro diario: la esquina la ocupa "Guardar cambios", que es lo
//     mas importante de esa pantalla.
//   - Login, registro, bienvenida, vista del veterinario y paginas
//     publicas: no hay sesion ni datos que consultar.
//
// CARGA SUS PROPIOS DATOS, sin depender de la pantalla donde este. Es
// menos eficiente que reusar lo que Analisis ya calculo, pero es la
// unica forma de que funcione en todas partes sin tocar seis archivos.
//
// Crea un componente y lo agrega al layout. Si algo no calza, ABORTA
// sin escribir NADA.
// ============================================================

const RUTA_COMP = 'components/ChiquiFlotante.tsx';
const RUTA_LAYOUT = 'app/layout.tsx';
const COMP_B64 = 'J3VzZSBjbGllbnQnCmltcG9ydCB7IHVzZVN0YXRlLCB1c2VFZmZlY3QgfSBmcm9tICdyZWFjdCcKaW1wb3J0IHsgdXNlUGF0aG5hbWUgfSBmcm9tICduZXh0L25hdmlnYXRpb24nCmltcG9ydCB7IGNyZWF0ZUNsaWVudCB9IGZyb20gJ0AvdXRpbHMvc3VwYWJhc2UvY2xpZW50JwppbXBvcnQgeyBkZXRlcm1pbmFyTWFzY290YUFjdGl2YSB9IGZyb20gJ0AvdXRpbHMvbWFzY290YUFjdGl2YScKaW1wb3J0IENoaXF1aUNoYXQsIHsgdHlwZSBEYXRvc0NoYXQgfSBmcm9tICdAL2NvbXBvbmVudHMvQ2hpcXVpQ2hhdCcKCi8vID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQovLyBDSElRVUkgRkxPVEFOVEUg4oCUIGVsIGNoYXQgZW4gY3VhbHF1aWVyIHBhbnRhbGxhCi8vID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQovLyBFbiBBbsOhbGlzaXMgZWwgY2hhdCBlcyB1bmEgdGFyamV0YSBkZW50cm8gZGVsIGNvbnRlbmlkby4gQWPDoSBlcyB1bmEKLy8gYnVyYnVqYSBmaWphIGFiYWpvIGEgbGEgZGVyZWNoYSwgcGFyYSBxdWUgc2UgcHVlZGEgcHJlZ3VudGFyIGRlc2RlCi8vIGRvbmRlIHVubyBlc3TDqSBzaW4gdGVuZXIgcXVlIGlyIGEgYnVzY2FybG8uCi8vCi8vIENBUkdBIFNVUyBQUk9QSU9TIERBVE9TLCBzaW4gZGVwZW5kZXIgZGUgbGEgcGFudGFsbGEgZG9uZGUgZXN0w6kuIEVzCi8vIG1lbm9zIGVmaWNpZW50ZSBxdWUgcmV1c2FyIGxvIHF1ZSBBbsOhbGlzaXMgeWEgY2FsY3Vsw7MsIHBlcm8gZXMgbGEKLy8gw7puaWNhIGZvcm1hIGRlIHF1ZSBmdW5jaW9uZSBlbiB0b2RhcyBwYXJ0ZXMgc2luIHRvY2FyIHNlaXMgYXJjaGl2b3MuCi8vCi8vIE5PIEFQQVJFQ0UgZW4gQW7DoWxpc2lzIChxdWUgeWEgbG8gdGllbmUgaW5jcnVzdGFkbyksIG5pIGVuIGVsCi8vIHJlZ2lzdHJvIGRpYXJpbyAoZG9uZGUgbGEgZXNxdWluYSBsYSBvY3VwYSAiR3VhcmRhciIpLCBuaSBlbiBsYXMKLy8gcGFudGFsbGFzIHNpbiBzZXNpw7NuLgoKY29uc3QgU0lOX0NIQVQgPSBbCiAgJy9sb2dpbicsICcvcmVnaXN0cm8nLCAnL2JpZW52ZW5pZGEnLCAnL3ZldCcsICcvcHJpdmFjaWRhZCcsICcvbGlua3MnLAogICcvYW5hbGlzaXMnLCAgICAgICAgLy8geWEgbG8gdGllbmUgY29tbyB0YXJqZXRhCiAgJy9yZWdpc3Ryby1kaWFyaW8nLCAvLyBhaMOtIG1hbmRhIGVsIGJvdMOzbiBkZSBndWFyZGFyCl0KCmNvbnN0IE1FU0VTID0gWydlbmUnLCAnZmViJywgJ21hcicsICdhYnInLCAnbWF5JywgJ2p1bicsICdqdWwnLCAnYWdvJywgJ3NlcCcsICdvY3QnLCAnbm92JywgJ2RpYyddCmNvbnN0IE1FU0VTX0xBUkdPID0gWydlbmVybycsICdmZWJyZXJvJywgJ21hcnpvJywgJ2FicmlsJywgJ21heW8nLCAnanVuaW8nLCAnanVsaW8nLAogICdhZ29zdG8nLCAnc2VwdGllbWJyZScsICdvY3R1YnJlJywgJ25vdmllbWJyZScsICdkaWNpZW1icmUnXQoKLy8gTG9zIG1pc21vcyB2YWxvcmVzIG5vcm1hbGVzIHkgZXRpcXVldGFzIHF1ZSB1c2EgQW7DoWxpc2lzLiBTaSBhbGfDum4KLy8gZMOtYSBjYW1iaWFuIGFsbMOhLCBoYXkgcXVlIGNhbWJpYXJsb3MgYWPDoSB0YW1iacOpbi4KY29uc3QgTk9STUFMRVM6IFJlY29yZDxzdHJpbmcsIHN0cmluZ1tdPiA9IHsKICBkaWdlc3Rpb246IFsnbm9ybWFsJ10sIGhlY2VzOiBbJ25vcm1hbCddLCBhcGV0aXRvOiBbJ25vcm1hbCddLCBhZ3VhOiBbJ25vcm1hbCddLAogIGVuZXJnaWE6IFsnbm9ybWFsJywgJ2FsdGEnLCAnbXV5X2FsdGEnXSwgYW5pbW86IFsnbm9ybWFsJywgJ2ZlbGl6JywgJ211eV9mZWxpeiddLAogIG1vdmlsaWRhZDogWydub3JtYWwnXSwgcGVsYWplOiBbJ2JyaWxsYW50ZScsICdub3JtYWwnXSwgY29uZHVjdGE6IFsnc29jaWFibGUnLCAnbm9ybWFsJ10sCiAgYXJlbmVybzogWydub3JtYWwnXSwKfQpjb25zdCBFVFE6IFJlY29yZDxzdHJpbmcsIHN0cmluZz4gPSB7CiAgJ2RpZ2VzdGlvbjp2b21pdG8nOiAndm9taXTDsycsICdkaWdlc3Rpb246ZGlhcnJlYSc6ICdkaWFycmVhJywgJ2RpZ2VzdGlvbjpuYXVzZWFzJzogJ27DoXVzZWFzJywKICAnZGlnZXN0aW9uOmdhc2VzJzogJ2dhc2VzJywgJ2RpZ2VzdGlvbjptYWxfYWxpZW50byc6ICdtYWwgYWxpZW50bycsCiAgJ2hlY2VzOmNvbl9zYW5ncmUnOiAnaGVjZXMgY29uIHNhbmdyZScsICdoZWNlczpibGFuZGFzJzogJ2hlY2VzIGJsYW5kYXMnLAogICdoZWNlczpkdXJhcyc6ICdoZWNlcyBkdXJhcycsICdoZWNlczpub19oaXpvJzogJ25vIGhpem8gaGVjZXMnLCAnaGVjZXM6ZGlhcnJlYSc6ICdkaWFycmVhJywKICAnYXBldGl0bzpuYWRhJzogJ25vIGNvbWnDsycsICdhcGV0aXRvOm1lbm9zJzogJ2NvbWnDsyBtZW5vcycsICdhcGV0aXRvOm1hcyc6ICdjb21pw7MgbcOhcycsCiAgJ2FndWE6bWVub3MnOiAndG9tw7MgbWVub3MgYWd1YScsICdhZ3VhOm1hcyc6ICd0b23DsyBtw6FzIGFndWEnLCAnYWd1YTpuYWRhJzogJ25vIHRvbcOzIGFndWEnLAogICdlbmVyZ2lhOm11eV9iYWphJzogJ2VuZXJnw61hIG11eSBiYWphJywgJ2VuZXJnaWE6YmFqYSc6ICdlbmVyZ8OtYSBiYWphJywKICAnYW5pbW86ZGVjYWlkbyc6ICdkZWNhw61kbycsICdhbmltbzphbnNpb3NvJzogJ2Fuc2lvc28nLCAnYW5pbW86aXJyaXRhYmxlJzogJ2lycml0YWJsZScsCiAgJ21vdmlsaWRhZDpjb2plcmEnOiAnY29qZXJhJywgJ21vdmlsaWRhZDpyaWdpZGV6JzogJ3JpZ2lkZXonLAogICdtb3ZpbGlkYWQ6ZGlmaWN1bHRhZCc6ICdkaWZpY3VsdGFkIGFsIG1vdmVyc2UnLAogICdwZWxhamU6cmFzY2EnOiAnc2UgcmFzY8OzJywgJ3BlbGFqZTpsYW1lX2V4Y2Vzbyc6ICdzZSBsYW1pw7MgbXVjaG8nLCAncGVsYWplOmNhaWRhJzogJ2Nhw61kYSBkZSBwZWxvJywKICAnY29uZHVjdGE6ZXNjb25kZSc6ICdzZSBlc2NvbmRpw7MnLCAnY29uZHVjdGE6YWdyZXNpdm8nOiAnYWdyZXNpdm8nLAogICdhcmVuZXJvOnNhbmdyZSc6ICdzYW5ncmUgZW4gbGEgb3JpbmEnLCAnYXJlbmVybzpkaWZpY3VsdGFkJzogJ2RpZmljdWx0YWQgYWwgb3JpbmFyJywKfQpjb25zdCBDVUlEQURPUzogeyBjYW1wbzogc3RyaW5nOyBsYWJlbDogc3RyaW5nOyBwYWxhYnJhczogc3RyaW5nW10gfVtdID0gWwogIHsgY2FtcG86ICdzZV9iYW5vJywgbGFiZWw6ICdCYcOxbycsIHBhbGFicmFzOiBbJ2JhbicsICdkdWNoYSddIH0sCiAgeyBjYW1wbzogJ2NvcnRlX3VuYXMnLCBsYWJlbDogJ0NvcnRlIGRlIHXDsWFzJywgcGFsYWJyYXM6IFsndW5hcycsICd1bml0YScsICdnYXJyYSddIH0sCiAgeyBjYW1wbzogJ2xpbXBpZXphX2RlbnRhbCcsIGxhYmVsOiAnTGltcGllemEgZGVudGFsJywgcGFsYWJyYXM6IFsnZGllbnRlJywgJ2RlbnRhbCcsICdjZXBpbGwnXSB9LAogIHsgY2FtcG86ICdsaW1waWV6YV9vaWRvcycsIGxhYmVsOiAnTGltcGllemEgZGUgb8OtZG9zJywgcGFsYWJyYXM6IFsnb2lkbycsICdvcmVqYSddIH0sCiAgeyBjYW1wbzogJ2NvbXByb19hbGltZW50bycsIGxhYmVsOiAnQ29tcHJhIGRlIGFsaW1lbnRvJywgcGFsYWJyYXM6IFsnY29tcHJhcicsICdzYWNvJywgJ2Nyb3F1ZXRhJ10gfSwKICB7IGNhbXBvOiAnY2FyZ29fZGlzcGVuc2Fkb3InLCBsYWJlbDogJ0Rpc3BlbnNhZG9yJywgcGFsYWJyYXM6IFsnZGlzcGVuc2Fkb3InXSB9LApdCgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBDaGlxdWlGbG90YW50ZSgpIHsKICBjb25zdCBwYXRobmFtZSA9IHVzZVBhdGhuYW1lKCkKICBjb25zdCBbZGF0b3MsIHNldERhdG9zXSA9IHVzZVN0YXRlPERhdG9zQ2hhdCB8IG51bGw+KG51bGwpCgogIGNvbnN0IG9jdWx0byA9ICFwYXRobmFtZSB8fCBTSU5fQ0hBVC5zb21lKHIgPT4gcGF0aG5hbWUgPT09IHIgfHwgcGF0aG5hbWUuc3RhcnRzV2l0aChyICsgJy8nKSkKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGlmIChvY3VsdG8pIHJldHVybgogICAgbGV0IHZpdm8gPSB0cnVlCgogICAgOyhhc3luYyAoKSA9PiB7CiAgICAgIGNvbnN0IHN1cGFiYXNlID0gY3JlYXRlQ2xpZW50KCkKICAgICAgY29uc3QgeyBkYXRhOiB7IHVzZXIgfSB9ID0gYXdhaXQgc3VwYWJhc2UuYXV0aC5nZXRVc2VyKCkKICAgICAgaWYgKCF1c2VyKSByZXR1cm4KCiAgICAgIGNvbnN0IHsgZGF0YTogbWFzY290YXMgfSA9IGF3YWl0IHN1cGFiYXNlCiAgICAgICAgLmZyb20oJ21hc2NvdGFzJykKICAgICAgICAuc2VsZWN0KCdpZCwgbm9tYnJlLCBlc3BlY2llJykKICAgICAgICAuZXEoJ3VzZXJfaWQnLCB1c2VyLmlkKQogICAgICAgIC5pcygnYXJjaGl2YWRhX2VuJywgbnVsbCkKICAgICAgaWYgKCFtYXNjb3RhcyB8fCBtYXNjb3Rhcy5sZW5ndGggPT09IDApIHJldHVybgoKICAgICAgY29uc3QgbSA9IGRldGVybWluYXJNYXNjb3RhQWN0aXZhKG1hc2NvdGFzKQogICAgICBpZiAoIW0pIHJldHVybgoKICAgICAgY29uc3QgaG95ID0gbmV3IEludGwuRGF0ZVRpbWVGb3JtYXQoJ2VuLUNBJywgeyB0aW1lWm9uZTogJ0FtZXJpY2EvU2FudGlhZ28nIH0pLmZvcm1hdChuZXcgRGF0ZSgpKQogICAgICAvLyBNZWRpb2TDrWE6IHJlc3RhciBkw61hcyBzb2JyZSBtZWRpYW5vY2hlIGZhbGxhIGVuIGxvcyBjYW1iaW9zIGRlCiAgICAgIC8vIGhvcmFyaW8gZGUgdmVyYW5vLgogICAgICBjb25zdCBkMzAgPSBuZXcgRGF0ZShob3kgKyAnVDEyOjAwOjAwJykKICAgICAgZDMwLnNldERhdGUoZDMwLmdldERhdGUoKSAtIDMwKQogICAgICBjb25zdCBkZXNkZSA9IG5ldyBJbnRsLkRhdGVUaW1lRm9ybWF0KCdlbi1DQScsIHsgdGltZVpvbmU6ICdBbWVyaWNhL1NhbnRpYWdvJyB9KS5mb3JtYXQoZDMwKQogICAgICBjb25zdCBpbmljaW9NZXMgPSBob3kuc2xpY2UoMCwgNykgKyAnLTAxJwoKICAgICAgY29uc3QgWwogICAgICAgIHsgZGF0YTogcmVncyB9LCB7IGRhdGE6IHBlc29zIH0sIHsgZGF0YTogdmFjIH0sIHsgZGF0YTogYW50IH0sCiAgICAgICAgeyBkYXRhOiBtZWRzIH0sIHsgZGF0YTogZXhzIH0sIHsgZGF0YTogdmlzaXRhc1QgfSwgeyBkYXRhOiBwYXNlb3MgfSwKICAgICAgXSA9IGF3YWl0IFByb21pc2UuYWxsKFsKICAgICAgICBzdXBhYmFzZS5mcm9tKCdyZWdpc3Ryb3NfZGlhcmlvcycpLnNlbGVjdCgnKicpLmVxKCdtYXNjb3RhX2lkJywgbS5pZCkKICAgICAgICAgIC5ndGUoJ2ZlY2hhJywgZGVzZGUpLm9yZGVyKCdmZWNoYScsIHsgYXNjZW5kaW5nOiBmYWxzZSB9KSwKICAgICAgICBzdXBhYmFzZS5mcm9tKCdoaXN0b3JpYWxfcGVzbycpLnNlbGVjdCgncGVzbywgZmVjaGEnKS5lcSgnbWFzY290YV9pZCcsIG0uaWQpCiAgICAgICAgICAub3JkZXIoJ2ZlY2hhJywgeyBhc2NlbmRpbmc6IGZhbHNlIH0pLmxpbWl0KDIpLAogICAgICAgIHN1cGFiYXNlLmZyb20oJ3ZhY3VuYXMnKS5zZWxlY3QoJ25vbWJyZSwgZmVjaGFfYXBsaWNhY2lvbiwgcHJveGltYV9mZWNoYScpCiAgICAgICAgICAuZXEoJ21hc2NvdGFfaWQnLCBtLmlkKS5vcmRlcignZmVjaGFfYXBsaWNhY2lvbicsIHsgYXNjZW5kaW5nOiBmYWxzZSB9KSwKICAgICAgICBzdXBhYmFzZS5mcm9tKCdhbnRpcGFyYXNpdGFyaW9zJykuc2VsZWN0KCdub21icmUsIGZlY2hhX2FwbGljYWNpb24sIHByb3hpbWFfZmVjaGEnKQogICAgICAgICAgLmVxKCdtYXNjb3RhX2lkJywgbS5pZCkub3JkZXIoJ2ZlY2hhX2FwbGljYWNpb24nLCB7IGFzY2VuZGluZzogZmFsc2UgfSksCiAgICAgICAgc3VwYWJhc2UuZnJvbSgnbWVkaWNhbWVudG9zJykuc2VsZWN0KCdub21icmUsIGZlY2hhX2luaWNpbywgZmVjaGFfZmluLCBlc3RhZG8nKQogICAgICAgICAgLmVxKCdtYXNjb3RhX2lkJywgbS5pZCksCiAgICAgICAgc3VwYWJhc2UuZnJvbSgnZXhhbWVuZXMnKS5zZWxlY3QoJ25vbWJyZSwgY2F0ZWdvcmlhLCBmZWNoYScpLmVxKCdtYXNjb3RhX2lkJywgbS5pZCkKICAgICAgICAgIC5vcmRlcignZmVjaGEnLCB7IGFzY2VuZGluZzogZmFsc2UgfSkubGltaXQoNSksCiAgICAgICAgc3VwYWJhc2UuZnJvbSgndmlzaXRhc192ZXRlcmluYXJpYXMnKS5zZWxlY3QoJ2ZlY2hhJykuZXEoJ21hc2NvdGFfaWQnLCBtLmlkKSwKICAgICAgICBzdXBhYmFzZS5mcm9tKCdyZWdpc3Ryb3NfZGlhcmlvcycpLnNlbGVjdCgnZmVjaGEsIHBhc2VvLCBwYXNlb19taW51dG9zX2V4YWN0b3MnKQogICAgICAgICAgLmVxKCdtYXNjb3RhX2lkJywgbS5pZCkuZ3RlKCdmZWNoYScsIGluaWNpb01lcykubHRlKCdmZWNoYScsIGhveSksCiAgICAgIF0pCgogICAgICBpZiAoIXZpdm8pIHJldHVybgoKICAgICAgY29uc3QgZm10ID0gKGY6IHN0cmluZyB8IG51bGwgfCB1bmRlZmluZWQpOiBzdHJpbmcgPT4gewogICAgICAgIGlmICghZikgcmV0dXJuICcnCiAgICAgICAgY29uc3QgZCA9IG5ldyBEYXRlKFN0cmluZyhmKS5zbGljZSgwLCAxMCkgKyAnVDEyOjAwOjAwJykKICAgICAgICByZXR1cm4gYCR7ZC5nZXREYXRlKCl9ICR7TUVTRVNbZC5nZXRNb250aCgpXX1gCiAgICAgIH0KICAgICAgY29uc3QgZGlhc0hhc3RhID0gKGY6IHN0cmluZyB8IG51bGwgfCB1bmRlZmluZWQpOiBudW1iZXIgfCBudWxsID0+IHsKICAgICAgICBpZiAoIWYpIHJldHVybiBudWxsCiAgICAgICAgY29uc3QgYSA9IG5ldyBEYXRlKGhveSArICdUMTI6MDA6MDAnKS5nZXRUaW1lKCkKICAgICAgICBjb25zdCBiID0gbmV3IERhdGUoU3RyaW5nKGYpLnNsaWNlKDAsIDEwKSArICdUMTI6MDA6MDAnKS5nZXRUaW1lKCkKICAgICAgICByZXR1cm4gTWF0aC5yb3VuZCgoYiAtIGEpIC8gODY0MDAwMDApCiAgICAgIH0KCiAgICAgIC8vIFNlw7FhbGVzIHN1ZWx0YXMgZGVsIHBlcsOtb2RvLgogICAgICBjb25zdCBzZW5hbGVzOiBEYXRvc0NoYXRbJ3NlbmFsZXMnXSA9IFtdCiAgICAgIGZvciAoY29uc3QgciBvZiAocmVncyB8fCBbXSkpIHsKICAgICAgICBpZiAoIXIuZmVjaGEpIGNvbnRpbnVlCiAgICAgICAgZm9yIChjb25zdCBbY2FtcG8sIG5vcm1hbGVzXSBvZiBPYmplY3QuZW50cmllcyhOT1JNQUxFUykpIHsKICAgICAgICAgIGNvbnN0IHYgPSAociBhcyBhbnkpW2NhbXBvXQogICAgICAgICAgaWYgKHYgJiYgIW5vcm1hbGVzLmluY2x1ZGVzKHYpKSB7CiAgICAgICAgICAgIHNlbmFsZXMhLnB1c2goewogICAgICAgICAgICAgIGNhbXBvLAogICAgICAgICAgICAgIGV0aXF1ZXRhOiBFVFFbYCR7Y2FtcG99OiR7dn1gXSB8fCBTdHJpbmcodikucmVwbGFjZSgvXy9nLCAnICcpLAogICAgICAgICAgICAgIGZlY2hhOiBmbXQoci5mZWNoYSksCiAgICAgICAgICAgICAgZmVjaGFJU086IFN0cmluZyhyLmZlY2hhKS5zbGljZSgwLCAxMCksCiAgICAgICAgICAgICAgbm90YTogKHIubm90YSB8fCAnJykudHJpbSgpLAogICAgICAgICAgICB9KQogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfQoKICAgICAgLy8gQ3VpZGFkb3M6IMO6bHRpbWEgdmV6IHkgY2FkYSBjdcOhbnRvLgogICAgICBjb25zdCBjdWlkYWRvcyA9IENVSURBRE9TLm1hcChjID0+IHsKICAgICAgICBjb25zdCBmZWNoYXMgPSAocmVncyB8fCBbXSkuZmlsdGVyKChyOiBhbnkpID0+IHJbYy5jYW1wb10pCiAgICAgICAgICAubWFwKChyOiBhbnkpID0+IFN0cmluZyhyLmZlY2hhKS5zbGljZSgwLCAxMCkpLnNvcnQoKS5yZXZlcnNlKCkKICAgICAgICBpZiAoZmVjaGFzLmxlbmd0aCA9PT0gMCkgcmV0dXJuIG51bGwKICAgICAgICBjb25zdCBkaWFzID0gTWF0aC5hYnMoZGlhc0hhc3RhKGZlY2hhc1swXSkgfHwgMCkKICAgICAgICBsZXQgY2FkYTogbnVtYmVyIHwgbnVsbCA9IG51bGwKICAgICAgICBpZiAoZmVjaGFzLmxlbmd0aCA+PSAyKSB7CiAgICAgICAgICBjb25zdCBkaWZzOiBudW1iZXJbXSA9IFtdCiAgICAgICAgICBmb3IgKGxldCBpID0gMDsgaSA8IE1hdGgubWluKGZlY2hhcy5sZW5ndGggLSAxLCA1KTsgaSsrKSB7CiAgICAgICAgICAgIGRpZnMucHVzaChNYXRoLnJvdW5kKAogICAgICAgICAgICAgIChuZXcgRGF0ZShmZWNoYXNbaV0gKyAnVDEyOjAwOjAwJykuZ2V0VGltZSgpIC0gbmV3IERhdGUoZmVjaGFzW2kgKyAxXSArICdUMTI6MDA6MDAnKS5nZXRUaW1lKCkpIC8gODY0MDAwMDAKICAgICAgICAgICAgKSkKICAgICAgICAgIH0KICAgICAgICAgIGNvbnN0IHByb20gPSBNYXRoLnJvdW5kKGRpZnMucmVkdWNlKChhLCBiKSA9PiBhICsgYiwgMCkgLyBkaWZzLmxlbmd0aCkKICAgICAgICAgIGlmIChwcm9tID4gMCkgY2FkYSA9IHByb20KICAgICAgICB9CiAgICAgICAgcmV0dXJuIHsgbGFiZWw6IGMubGFiZWwsIHBhbGFicmFzOiBjLnBhbGFicmFzLCBkaWFzRGVzZGU6IGRpYXMsIGNhZGFDdWFudG9zOiBjYWRhIH0KICAgICAgfSkuZmlsdGVyKEJvb2xlYW4pIGFzIERhdG9zQ2hhdFsnY3VpZGFkb3MnXQoKICAgICAgLy8gU29sbyBsYSBkb3NpcyBtw6FzIHJlY2llbnRlIGRlIGNhZGEgdGlwbzogbGEgcmVnbGEgZGVsIHByb3llY3RvLgogICAgICBjb25zdCBtYXNSZWNpZW50ZSA9IChsaXN0YTogYW55W10gfCBudWxsKSA9PiB7CiAgICAgICAgY29uc3QgcG9yTm9tYnJlID0gbmV3IE1hcDxzdHJpbmcsIGFueT4oKQogICAgICAgIGZvciAoY29uc3QgeCBvZiAobGlzdGEgfHwgW10pKSB7CiAgICAgICAgICBjb25zdCBrID0gKHgubm9tYnJlIHx8ICcnKS50b0xvd2VyQ2FzZSgpLnRyaW0oKQogICAgICAgICAgaWYgKCFwb3JOb21icmUuaGFzKGspKSBwb3JOb21icmUuc2V0KGssIHgpCiAgICAgICAgfQogICAgICAgIHJldHVybiBBcnJheS5mcm9tKHBvck5vbWJyZS52YWx1ZXMoKSkKICAgICAgfQoKICAgICAgLy8gTGFzIHZpc2l0YXMgdmllbmVuIGRlIERPUyBsdWdhcmVzLCBpZ3VhbCBxdWUgZW4gQW7DoWxpc2lzLgogICAgICBjb25zdCBmZWNoYXNWaXNpdGEgPSBuZXcgU2V0PHN0cmluZz4oKQogICAgICBmb3IgKGNvbnN0IHYgb2YgKHZpc2l0YXNUIHx8IFtdKSkgaWYgKHYuZmVjaGEpIGZlY2hhc1Zpc2l0YS5hZGQoU3RyaW5nKHYuZmVjaGEpLnNsaWNlKDAsIDEwKSkKICAgICAgZm9yIChjb25zdCByIG9mIChyZWdzIHx8IFtdKSkgaWYgKChyIGFzIGFueSkuZnVlX2FsX3ZldCAmJiByLmZlY2hhKSBmZWNoYXNWaXNpdGEuYWRkKFN0cmluZyhyLmZlY2hhKS5zbGljZSgwLCAxMCkpCgogICAgICBjb25zdCBNSU5fUkFOR086IFJlY29yZDxzdHJpbmcsIG51bWJlcj4gPSB7ICcxMF8zMG1pbic6IDIwLCAnMzBtaW5fMWgnOiA0NSwgJzFfMmgnOiA5MCwgJzJfNGgnOiAxODAgfQogICAgICBjb25zdCBwYXNlb3NNZXMgPSAocGFzZW9zIHx8IFtdKS5maWx0ZXIoKHI6IGFueSkgPT4gci5wYXNlbyAmJiByLnBhc2VvICE9PSAnbm9fcGFzZW8nKQogICAgICBjb25zdCBtaW51dG9zTWVzID0gcGFzZW9zTWVzLnJlZHVjZSgoYWNjOiBudW1iZXIsIHI6IGFueSkgPT4KICAgICAgICBhY2MgKyAodHlwZW9mIHIucGFzZW9fbWludXRvc19leGFjdG9zID09PSAnbnVtYmVyJyAmJiByLnBhc2VvX21pbnV0b3NfZXhhY3RvcyA+IDAKICAgICAgICAgID8gci5wYXNlb19taW51dG9zX2V4YWN0b3MgOiAoTUlOX1JBTkdPW3IucGFzZW9dIHx8IDApKSwgMCkKCiAgICAgIGNvbnN0IGFjdGl2b3MgPSAobWVkcyB8fCBbXSkuZmlsdGVyKCh4OiBhbnkpID0+CiAgICAgICAgeC5lc3RhZG8gPT09ICdhY3Rpdm8nICYmICgheC5mZWNoYV9pbmljaW8gfHwgeC5mZWNoYV9pbmljaW8gPD0gaG95KSAmJiAoIXguZmVjaGFfZmluIHx8IHguZmVjaGFfZmluID49IGhveSkpCgogICAgICBzZXREYXRvcyh7CiAgICAgICAgbm9tYnJlOiBtLm5vbWJyZSB8fCAndHUgbWFzY290YScsCiAgICAgICAgZXNwZWNpZTogbS5lc3BlY2llIHx8ICcnLAogICAgICAgIC8vIExhIGJ1cmJ1amEgbm8gbXVlc3RyYSBlcGlzb2Rpb3MgYWdydXBhZG9zOiBlc28gdml2ZSBlbgogICAgICAgIC8vIEFuw6FsaXNpcywgcXVlIHRpZW5lIGVsIGPDoWxjdWxvIGNvbXBsZXRvLgogICAgICAgIGVwaXNvZGlvczogW10sCiAgICAgICAgdG90YWxSZWdpc3Ryb3M6IChyZWdzIHx8IFtdKS5sZW5ndGgsCiAgICAgICAgcGN0QmllbjogMCwKICAgICAgICB0ZXh0b1BlcmlvZG86ICdsb3Mgw7psdGltb3MgMzAgZMOtYXMnLAogICAgICAgIHBhc2Vvc01lczogbS5lc3BlY2llID09PSAnUGVycm8nCiAgICAgICAgICA/IHsgY2FudGlkYWQ6IHBhc2Vvc01lcy5sZW5ndGgsIG1pbnV0b3M6IG1pbnV0b3NNZXMsIG5vbWJyZU1lczogTUVTRVNfTEFSR09bTnVtYmVyKGhveS5zbGljZSg1LCA3KSkgLSAxXSB9CiAgICAgICAgICA6IG51bGwsCiAgICAgICAgcGVzbzogcGVzb3MgJiYgcGVzb3MubGVuZ3RoID4gMAogICAgICAgICAgPyB7IGFjdHVhbDogcGVzb3NbMF0ucGVzbywgZmVjaGE6IGZtdChwZXNvc1swXS5mZWNoYSksIGFudGVyaW9yOiBwZXNvcy5sZW5ndGggPiAxID8gcGVzb3NbMV0ucGVzbyA6IG51bGwgfQogICAgICAgICAgOiBudWxsLAogICAgICAgIG1lZGljYW1lbnRvczogYWN0aXZvcy5tYXAoKHg6IGFueSkgPT4gKHsgbm9tYnJlOiB4Lm5vbWJyZSB8fCAnTWVkaWNhbWVudG8nLCBkZXNkZTogZm10KHguZmVjaGFfaW5pY2lvKSB9KSksCiAgICAgICAgdmFjdW5hczogbWFzUmVjaWVudGUodmFjKS5tYXAoKHY6IGFueSkgPT4gKHsKICAgICAgICAgIG5vbWJyZTogdi5ub21icmUgfHwgJ1ZhY3VuYScsCiAgICAgICAgICBwcm94aW1hOiB2LnByb3hpbWFfZmVjaGEgPyBmbXQodi5wcm94aW1hX2ZlY2hhKSA6IG51bGwsCiAgICAgICAgICBkaWFzOiBkaWFzSGFzdGEodi5wcm94aW1hX2ZlY2hhKSwKICAgICAgICB9KSksCiAgICAgICAgYW50aXBhcmFzaXRhcmlvczogbWFzUmVjaWVudGUoYW50KS5tYXAoKGE6IGFueSkgPT4gKHsKICAgICAgICAgIG5vbWJyZTogYS5ub21icmUgfHwgJ0FudGlwYXJhc2l0YXJpbycsCiAgICAgICAgICBwcm94aW1hOiBhLnByb3hpbWFfZmVjaGEgPyBmbXQoYS5wcm94aW1hX2ZlY2hhKSA6IG51bGwsCiAgICAgICAgICBkaWFzOiBkaWFzSGFzdGEoYS5wcm94aW1hX2ZlY2hhKSwKICAgICAgICB9KSksCiAgICAgICAgc2VuYWxlcywKICAgICAgICBjdWlkYWRvcywKICAgICAgICBleGFtZW5lczogKGV4cyB8fCBbXSkubWFwKChlOiBhbnkpID0+ICh7CiAgICAgICAgICBub21icmU6IGUubm9tYnJlIHx8IGUuY2F0ZWdvcmlhIHx8ICdFeGFtZW4nLAogICAgICAgICAgZmVjaGE6IGZtdChlLmZlY2hhKSwKICAgICAgICB9KSksCiAgICAgICAgdmlzaXRhc1ZldDogQXJyYXkuZnJvbShmZWNoYXNWaXNpdGEpLnNvcnQoKSwKICAgICAgICBmbXRWaXNpdGE6IGZtdCwKICAgICAgfSkKICAgIH0pKCkKCiAgICByZXR1cm4gKCkgPT4geyB2aXZvID0gZmFsc2UgfQogIH0sIFtvY3VsdG8sIHBhdGhuYW1lXSkKCiAgaWYgKG9jdWx0byB8fCAhZGF0b3MpIHJldHVybiBudWxsCiAgcmV0dXJuIDxDaGlxdWlDaGF0IGRhdG9zPXtkYXRvc30gZmxvdGFudGUgLz4KfQo=';

function contar(texto, buscado) {
  return texto.split(buscado).length - 1;
}

function abortar(motivo) {
  console.log('');
  console.log('ABORTADO: ' + motivo);
  console.log('No se modifico NINGUN archivo. Avisale a Claude lo que dice este mensaje.');
  process.exit(1);
}

const destinoComp = path.join(process.cwd(), RUTA_COMP);
const destinoLayout = path.join(process.cwd(), RUTA_LAYOUT);

if (fs.existsSync(destinoComp)) {
  abortar('ya existe ' + RUTA_COMP + '. No lo sobrescribo por si tiene cambios tuyos.');
}
if (!fs.existsSync(destinoLayout)) {
  abortar('no se encontro ' + RUTA_LAYOUT + '.');
}
// El chat tiene que aceptar el modo flotante.
const chat = path.join(process.cwd(), 'components/ChiquiChat.tsx');
if (!fs.existsSync(chat)) {
  abortar('falta components/ChiquiChat.tsx.');
}
if (!fs.readFileSync(chat, 'utf8').includes('flotante = false')) {
  abortar('el chat no acepta el modo flotante. Corre primero el script 456.');
}
console.log('  OK  el chat acepta el modo flotante');

let layout = fs.readFileSync(destinoLayout, 'utf8');
if (layout.includes('ChiquiFlotante')) {
  abortar('el layout ya tiene el chat flotante. Parece que este script ya se corrio.');
}

// --- Insertar en el body
const M = layout.match(/<body[^>]*>/);
if (!M) {
  abortar('no encontre la etiqueta body en el layout.');
}
const posBody = layout.indexOf(M[0]) + M[0].length;
layout = layout.slice(0, posBody)
  + '\n        {/* Chat de Chiqui, disponible en cualquier pantalla. Ver\n            components/ChiquiFlotante.tsx para dónde NO aparece. */}\n        <ChiquiFlotante />'
  + layout.slice(posBody);
console.log('  OK  punto de insercion en el layout');

// --- Import despues del ultimo que haya
const lineas = layout.split('\n');
let ultimo = -1;
for (let i = 0; i < lineas.length; i++) {
  if (lineas[i].startsWith('import ')) ultimo = i;
}
if (ultimo === -1) {
  abortar('no encontre ningun import en el layout.');
}
lineas.splice(ultimo + 1, 0, "import ChiquiFlotante from '@/components/ChiquiFlotante'");
layout = lineas.join('\n');
console.log('  OK  import agregado');

const comp = Buffer.from(COMP_B64, 'base64').toString('utf8');
for (const r of ["'use client'", 'export default function ChiquiFlotante', 'SIN_CHAT', 'flotante']) {
  if (!comp.includes(r)) {
    abortar('el componente no incluye [' + r + ']. Script corrupto.');
  }
}

// --- Verificaciones
if (contar(layout, '<ChiquiFlotante />') !== 1) {
  abortar('el chat no quedo exactamente una vez en el layout.');
}
if (layout.indexOf("import ChiquiFlotante") > layout.indexOf('<ChiquiFlotante />')) {
  abortar('el import quedaria despues del uso.');
}

const carpeta = path.dirname(destinoComp);
if (!fs.existsSync(carpeta)) fs.mkdirSync(carpeta, { recursive: true });
fs.writeFileSync(destinoComp, comp, 'utf8');
console.log('');
console.log('OK: ' + RUTA_COMP);
fs.writeFileSync(destinoLayout, layout, 'utf8');
console.log('OK: ' + RUTA_LAYOUT);
console.log('');
console.log('Listo. Chiqui ya se puede consultar desde cualquier pantalla.');
