// Script: generar_61_qr_instalar_app.js
// Que hace: hace que el QR de descarga dispare el cuadro de instalacion
// de Chrome/Android automaticamente apenas cargue la pagina, en vez de
// esperar a que la persona navegue un rato para que aparezca el banner.
//
// La imagen del QR apunta a:
//   https://chiqui-beta-lilac.vercel.app/login?instalar=true
// (apunta a /login porque es la ruta publica que no redirige ni pierde
// el parametro -- la raiz / redirige a /login y pierde el ?instalar=true
// en el camino).
//
// En iPhone este componente no hace nada (Apple no permite que ningun
// sitio dispare instalacion automatica bajo ninguna circunstancia) --
// en iPhone la persona sigue viendo las instrucciones manuales de
// "agregar a inicio" que ya estan en Perfil.
//
//   1) components/InstalarAutomatico.tsx (ARCHIVO NUEVO) -- escucha el
//      evento beforeinstallprompt y lo dispara apenas este disponible,
//      SOLO si la URL tiene ?instalar=true. En cualquier otra pagina no
//      hace nada (el parametro no esta, el componente no actua).
//
//   2) app/layout.tsx (REEMPLAZA el existente) -- incluye el componente
//      nuevo envuelto en <Suspense> (necesario porque usa useSearchParams,
//      que requiere Suspense en Next.js para no romper el build).
//
// Como correrlo: node generar_61_qr_instalar_app.js
// Confirma "OK" para ambos archivos

const fs = require('fs');
const path = require('path');

function escribir(relPath, b64) {
  const filePath = path.join(...relPath.split('/'));
  const content = Buffer.from(b64, 'base64').toString('utf8');
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('OK: ' + filePath);
}

escribir('components/InstalarAutomatico.tsx', "J3VzZSBjbGllbnQnCmltcG9ydCB7IHVzZUVmZmVjdCwgdXNlU3RhdGUgfSBmcm9tICdyZWFjdCcKaW1wb3J0IHsgdXNlU2VhcmNoUGFyYW1zIH0gZnJvbSAnbmV4dC9uYXZpZ2F0aW9uJwoKLy8gU2kgbGEgcGVyc29uYSBsbGVnYSBjb24gP2luc3RhbGFyPXRydWUgZW4gbGEgVVJMIChjb21vIHBhc2EgYWwKLy8gZXNjYW5lYXIgZWwgUVIgZGUgZGVzY2FyZ2EpLCBlc3RlIGNvbXBvbmVudGUgZGlzcGFyYSBlbCBjdWFkcm8gZGUKLy8gaW5zdGFsYWNpb24gZGUgQ2hyb21lL0FuZHJvaWQgYXV0b21hdGljYW1lbnRlLCBhcGVuYXMgZWwgbmF2ZWdhZG9yIGxvCi8vIHRlbmdhIGRpc3BvbmlibGUgLS0gc2luIGVzcGVyYXIgYSBxdWUgbGEgcGVyc29uYSBuYXZlZ3VlIHVuIHJhdG8KLy8gcGFyYSBxdWUgYXBhcmV6Y2EgZWwgYmFubmVyIG5vcm1hbC4KLy8KLy8gRW4gaVBob25lIGVzdG8gbm8gaGFjZSBuYWRhIChBcHBsZSBubyBwZXJtaXRlIHF1ZSBuaW5ndW4gc2l0aW8KLy8gZGlzcGFyZSBpbnN0YWxhY2lvbiBhdXRvbWF0aWNhIGJham8gbmluZ3VuYSBjaXJjdW5zdGFuY2lhKSwgYXNpIHF1ZQovLyBlbiBpUGhvbmUgbGEgcGVyc29uYSBzaWd1ZSB2aWVuZG8gbGFzIGluc3RydWNjaW9uZXMgbWFudWFsZXMgZGUKLy8gImFncmVnYXIgYSBpbmljaW8iIHF1ZSB5YSBlc3RhbiBlbiBQZXJmaWwuCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIEluc3RhbGFyQXV0b21hdGljbygpIHsKICBjb25zdCBzZWFyY2hQYXJhbXMgPSB1c2VTZWFyY2hQYXJhbXMoKQogIGNvbnN0IFtldmVudG9JbnN0YWxhY2lvbiwgc2V0RXZlbnRvSW5zdGFsYWNpb25dID0gdXNlU3RhdGU8YW55PihudWxsKQogIGNvbnN0IHZpZW5lRGVsUVIgPSBzZWFyY2hQYXJhbXMuZ2V0KCdpbnN0YWxhcicpID09PSAndHJ1ZScKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGlmICghdmllbmVEZWxRUikgcmV0dXJuCgogICAgZnVuY3Rpb24gbWFuZWphckJlZm9yZUluc3RhbGxQcm9tcHQoZTogRXZlbnQpIHsKICAgICAgZS5wcmV2ZW50RGVmYXVsdCgpCiAgICAgIHNldEV2ZW50b0luc3RhbGFjaW9uKGUpCiAgICB9CiAgICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignYmVmb3JlaW5zdGFsbHByb21wdCcsIG1hbmVqYXJCZWZvcmVJbnN0YWxsUHJvbXB0KQogICAgcmV0dXJuICgpID0+IHdpbmRvdy5yZW1vdmVFdmVudExpc3RlbmVyKCdiZWZvcmVpbnN0YWxscHJvbXB0JywgbWFuZWphckJlZm9yZUluc3RhbGxQcm9tcHQpCiAgfSwgW3ZpZW5lRGVsUVJdKQoKICB1c2VFZmZlY3QoKCkgPT4gewogICAgaWYgKCFldmVudG9JbnN0YWxhY2lvbikgcmV0dXJuCiAgICAvLyBBcGVuYXMgZWwgZXZlbnRvIGVzdGUgZGlzcG9uaWJsZSwgZGlzcGFyYW1vcyBlbCBjdWFkcm8gZGUKICAgIC8vIGluc3RhbGFjaW9uIHNpbiBlc3BlcmFyIGEgcXVlIGxhIHBlcnNvbmEgdG9xdWUgbmFkYS4KICAgIGV2ZW50b0luc3RhbGFjaW9uLnByb21wdCgpCiAgfSwgW2V2ZW50b0luc3RhbGFjaW9uXSkKCiAgcmV0dXJuIG51bGwKfQo=");
escribir('app/layout.tsx', "aW1wb3J0IHR5cGUgeyBNZXRhZGF0YSwgVmlld3BvcnQgfSBmcm9tICduZXh0JwppbXBvcnQgeyBOdW5pdG8sIE51bml0b19TYW5zIH0gZnJvbSAnbmV4dC9mb250L2dvb2dsZScKaW1wb3J0IHsgU3VzcGVuc2UgfSBmcm9tICdyZWFjdCcKaW1wb3J0ICcuL2dsb2JhbHMuY3NzJwppbXBvcnQgUmVnaXN0cmFyU2VydmljZVdvcmtlciBmcm9tICdAL2NvbXBvbmVudHMvUmVnaXN0cmFyU2VydmljZVdvcmtlcicKaW1wb3J0IEluc3RhbGFyQXV0b21hdGljbyBmcm9tICdAL2NvbXBvbmVudHMvSW5zdGFsYXJBdXRvbWF0aWNvJwoKY29uc3QgbnVuaXRvID0gTnVuaXRvKHsKICBzdWJzZXRzOiBbJ2xhdGluJ10sCiAgd2VpZ2h0OiBbJzQwMCcsICc2MDAnLCAnNzAwJywgJzgwMCddLAogIHZhcmlhYmxlOiAnLS1mb250LW51bml0bycsCn0pCgpjb25zdCBudW5pdG9TYW5zID0gTnVuaXRvX1NhbnMoewogIHN1YnNldHM6IFsnbGF0aW4nXSwKICB3ZWlnaHQ6IFsnNDAwJywgJzYwMCddLAogIHZhcmlhYmxlOiAnLS1mb250LW51bml0by1zYW5zJywKfSkKCmV4cG9ydCBjb25zdCBtZXRhZGF0YTogTWV0YWRhdGEgPSB7CiAgdGl0bGU6ICdDSElRVUkgRW50cmUgU2XDsWFsZXMnLAogIGRlc2NyaXB0aW9uOiAnVHUgY29tcGHDsWVybyBkZSBvYnNlcnZhY2nDs24geSBjdWlkYWRvLicsCiAgbWFuaWZlc3Q6ICcvbWFuaWZlc3Qud2VibWFuaWZlc3QnLAogIGFwcGxlV2ViQXBwOiB7CiAgICBjYXBhYmxlOiB0cnVlLAogICAgc3RhdHVzQmFyU3R5bGU6ICdkZWZhdWx0JywKICAgIHRpdGxlOiAnQ0hJUVVJJywKICB9LAogIGljb25zOiB7CiAgICBpY29uOiAnL2ljb24tNTEyeDUxMi5wbmcnLAogICAgYXBwbGU6ICcvYXBwbGUtdG91Y2gtaWNvbi5wbmcnLAogIH0sCn0KCmV4cG9ydCBjb25zdCB2aWV3cG9ydDogVmlld3BvcnQgPSB7CiAgd2lkdGg6ICdkZXZpY2Utd2lkdGgnLAogIGluaXRpYWxTY2FsZTogMSwKICBtYXhpbXVtU2NhbGU6IDEsCiAgdGhlbWVDb2xvcjogJyM4QzU3MkYnLAp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBSb290TGF5b3V0KHsgY2hpbGRyZW4gfTogeyBjaGlsZHJlbjogUmVhY3QuUmVhY3ROb2RlIH0pIHsKICByZXR1cm4gKAogICAgPGh0bWwgbGFuZz0iZXMiPgogICAgICA8Ym9keSBjbGFzc05hbWU9e2Ake251bml0by52YXJpYWJsZX0gJHtudW5pdG9TYW5zLnZhcmlhYmxlfSBmb250LWJvZHkgYmctWyNGNUVERTNdIHRleHQtWyMzRDJCMUZdIG1pbi1oLXNjcmVlbmB9PgogICAgICAgIDxSZWdpc3RyYXJTZXJ2aWNlV29ya2VyIC8+CiAgICAgICAgPFN1c3BlbnNlIGZhbGxiYWNrPXtudWxsfT4KICAgICAgICAgIDxJbnN0YWxhckF1dG9tYXRpY28gLz4KICAgICAgICA8L1N1c3BlbnNlPgogICAgICAgIHtjaGlsZHJlbn0KICAgICAgPC9ib2R5PgogICAgPC9odG1sPgogICkKfQo=");
