const fs = require('fs');
const path = require('path');

// ============================================================
// generar_323_linkvet_reusa_vigente.js
// ============================================================
// Reescribe components/LinkVet.tsx (el de la pagina Perfil).
//
// PROBLEMA QUE ARREGLA:
// La version anterior hacia un INSERT en links_veterinario en CADA
// toque del boton, sin revisar si ya existia un link vigente. Cada
// clic dejaba una fila nueva con un token distinto. Ademas, al
// recargar el Perfil el link desaparecia de la vista, asi que la
// persona volvia a apretar "Generar" y creaba otro mas.
//
// AHORA:
//  1. Al abrir el Perfil busca un link vigente (activo y sin expirar)
//     de esa mascota y lo muestra de inmediato.
//  2. El boton de generar solo aparece si NO hay ninguno vigente.
//  3. Antes de insertar vuelve a chequear, por si aparecio uno desde
//     el Dashboard mientras tanto.
//  4. Muestra hasta cuando sirve el link (antes nadie sabia que
//     expiraba a los 7 dias).
//
// ANTES DE ESCRIBIR verifica que el archivo actual sea el esperado.
// Si no lo es, ABORTA sin tocar nada.
// ============================================================

const RUTA = 'components/LinkVet.tsx';

const LINKVET_B64 = 'J3VzZSBjbGllbnQnCmltcG9ydCB7IHVzZVN0YXRlLCB1c2VFZmZlY3QgfSBmcm9tICdyZWFjdCcKaW1wb3J0IHsgY3JlYXRlQ2xpZW50IH0gZnJvbSAnQC91dGlscy9zdXBhYmFzZS9jbGllbnQnCgovLyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KLy8gTElOSyBWRVQg4oCUIGNvbXBhcnRpciBlbCBoaXN0b3JpYWwgY29uIGVsIHZldGVyaW5hcmlvIChQZXJmaWwpCi8vID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQovLyBRVUUgQ0FNQklPIFkgUE9SIFFVRToKLy8KLy8gTGEgdmVyc2lvbiBhbnRlcmlvciBoYWNpYSB1biBJTlNFUlQgZW4gbGlua3NfdmV0ZXJpbmFyaW8gZW4gQ0FEQQovLyB0b3F1ZSBkZWwgYm90b24sIHNpbiByZXZpc2FyIHNpIHlhIGV4aXN0aWEgdW4gbGluayB2aWdlbnRlLiBDYWRhCi8vIGNsaWMgZGVqYWJhIHVuYSBmaWxhIG51ZXZhIGNvbiB1biB0b2tlbiBkaXN0aW50byAodW5hIGN1ZW50YSBkZQovLyBwcnVlYmEgbGxlZ28gYSBhY3VtdWxhciA1MikuIEFkZW1hcywgYWwgcmVjYXJnYXIgbGEgcGFnaW5hIGVsIGxpbmsKLy8gZ2VuZXJhZG8gZGVzYXBhcmVjaWEgZGUgbGEgdmlzdGEgeSBsYSBwZXJzb25hIHZvbHZpYSBhIGFwcmV0YXIKLy8gIkdlbmVyYXIiLCBjcmVhbmRvIG90cm8gbWFzLgovLwovLyBBaG9yYToKLy8gIDEuIEFsIGFicmlyIGVsIFBlcmZpbCBzZSBidXNjYSB1biBsaW5rIFZJR0VOVEUgKGFjdGl2byB5IHNpbgovLyAgICAgZXhwaXJhcikgZGUgZXN0YSBtYXNjb3RhLiBTaSBleGlzdGUsIHNlIG11ZXN0cmEgZGUgaW5tZWRpYXRvLgovLyAgMi4gRWwgYm90b24gc29sbyBhcGFyZWNlIGN1YW5kbyBOTyBoYXkgbmluZ3VubyB2aWdlbnRlLgovLyAgMy4gU2UgbXVlc3RyYSBoYXN0YSBjdWFuZG8gc2lydmUgZWwgbGluay4gQW50ZXMgbmFkaWUgc2FiaWEgcXVlCi8vICAgICBleHBpcmFiYSBhIGxvcyA3IGRpYXM6IHNpIGVsIHZldGVyaW5hcmlvIGxvIGFicmlhIGRlc3B1ZXMsIG5vCi8vICAgICBmdW5jaW9uYWJhIHkgbm8gaGFiaWEgZm9ybWEgZGUgZW50ZW5kZXIgcG9yIHF1ZS4KLy8KLy8gTm90YSBzb2JyZSB0b0lTT1N0cmluZygpOiBsYSByZWdsYSBkZWwgcHJveWVjdG8gbG8gcHJvaGliZSBwYXJhCi8vIG9idGVuZXIgZWwgRElBIChhaGkgdmEgSW50bCBjb24gQW1lcmljYS9TYW50aWFnbykuIEFjYSBzZSBjb21wYXJhIHVuCi8vIHRpbWVzdGFtcHR6IGNvbnRyYSAiYWhvcmEiLCBxdWUgZXMgdW4gaW5zdGFudGUgeSBubyB1biBkaWEg4oCUIHBhcmEKLy8gZXNvIGVsIGZvcm1hdG8gVVRDIGVzIGp1c3RhbWVudGUgZWwgY29ycmVjdG8uCgpmdW5jdGlvbiBmbXRFeHBpcmEoaXNvOiBzdHJpbmcpOiBzdHJpbmcgewogIGNvbnN0IGQgPSBuZXcgRGF0ZShpc28pCiAgY29uc3QgbXMgPSBbJ2VuZXJvJywgJ2ZlYnJlcm8nLCAnbWFyem8nLCAnYWJyaWwnLCAnbWF5bycsICdqdW5pbycsICdqdWxpbycsICdhZ29zdG8nLCAnc2VwdGllbWJyZScsICdvY3R1YnJlJywgJ25vdmllbWJyZScsICdkaWNpZW1icmUnXQogIHJldHVybiBgJHtkLmdldERhdGUoKX0gZGUgJHttc1tkLmdldE1vbnRoKCldfWAKfQoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gTGlua1ZldCh7IG1hc2NvdGFJZCB9OiB7IG1hc2NvdGFJZDogc3RyaW5nIH0pIHsKICBjb25zdCBzdXBhYmFzZSA9IGNyZWF0ZUNsaWVudCgpCiAgY29uc3QgW2xpbmssIHNldExpbmtdID0gdXNlU3RhdGUoJycpCiAgY29uc3QgW2V4cGlyYSwgc2V0RXhwaXJhXSA9IHVzZVN0YXRlKCcnKQogIGNvbnN0IFtsb2FkaW5nLCBzZXRMb2FkaW5nXSA9IHVzZVN0YXRlKGZhbHNlKQogIGNvbnN0IFtidXNjYW5kbywgc2V0QnVzY2FuZG9dID0gdXNlU3RhdGUodHJ1ZSkKICBjb25zdCBbY29waWFkbywgc2V0Q29waWFkb10gPSB1c2VTdGF0ZShmYWxzZSkKICBjb25zdCBbZXJyb3IsIHNldEVycm9yXSA9IHVzZVN0YXRlKCcnKQoKICAvLyBBbCBtb250YXI6IHNpIHlhIGhheSB1biBsaW5rIHZpZ2VudGUgcGFyYSBlc3RhIG1hc2NvdGEsIHNlIG11ZXN0cmEKICAvLyBlbiB2ZXogZGUgb2ZyZWNlciBnZW5lcmFyIG90cm8uCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGxldCBjYW5jZWxhZG8gPSBmYWxzZQogICAgOyhhc3luYyAoKSA9PiB7CiAgICAgIHNldEJ1c2NhbmRvKHRydWUpCiAgICAgIGNvbnN0IHZpZ2VudGUgPSBhd2FpdCBidXNjYXJWaWdlbnRlKCkKICAgICAgaWYgKCFjYW5jZWxhZG8pIHsKICAgICAgICBpZiAodmlnZW50ZSkgewogICAgICAgICAgc2V0TGluayhgJHt3aW5kb3cubG9jYXRpb24ub3JpZ2lufS92ZXQ/dG9rZW49JHt2aWdlbnRlLnRva2VufWApCiAgICAgICAgICBzZXRFeHBpcmEodmlnZW50ZS5leHBpcmFfZW4pCiAgICAgICAgfQogICAgICAgIHNldEJ1c2NhbmRvKGZhbHNlKQogICAgICB9CiAgICB9KSgpCiAgICByZXR1cm4gKCkgPT4geyBjYW5jZWxhZG8gPSB0cnVlIH0KICAgIC8vIGVzbGludC1kaXNhYmxlLW5leHQtbGluZSByZWFjdC1ob29rcy9leGhhdXN0aXZlLWRlcHMKICB9LCBbbWFzY290YUlkXSkKCiAgYXN5bmMgZnVuY3Rpb24gYnVzY2FyVmlnZW50ZSgpOiBQcm9taXNlPHsgdG9rZW46IHN0cmluZzsgZXhwaXJhX2VuOiBzdHJpbmcgfSB8IG51bGw+IHsKICAgIGNvbnN0IGFob3JhID0gbmV3IERhdGUoKS50b0lTT1N0cmluZygpCiAgICBjb25zdCB7IGRhdGEgfSA9IGF3YWl0IHN1cGFiYXNlCiAgICAgIC5mcm9tKCdsaW5rc192ZXRlcmluYXJpbycpCiAgICAgIC5zZWxlY3QoJ3Rva2VuLCBleHBpcmFfZW4nKQogICAgICAuZXEoJ21hc2NvdGFfaWQnLCBtYXNjb3RhSWQpCiAgICAgIC5lcSgnYWN0aXZvJywgdHJ1ZSkKICAgICAgLmd0KCdleHBpcmFfZW4nLCBhaG9yYSkKICAgICAgLm9yZGVyKCdjcmVhdGVkX2F0JywgeyBhc2NlbmRpbmc6IGZhbHNlIH0pCiAgICAgIC5saW1pdCgxKQogICAgaWYgKGRhdGEgJiYgZGF0YS5sZW5ndGggPiAwICYmIGRhdGFbMF0udG9rZW4pIHsKICAgICAgcmV0dXJuIHsgdG9rZW46IGRhdGFbMF0udG9rZW4gYXMgc3RyaW5nLCBleHBpcmFfZW46IGRhdGFbMF0uZXhwaXJhX2VuIGFzIHN0cmluZyB9CiAgICB9CiAgICByZXR1cm4gbnVsbAogIH0KCiAgYXN5bmMgZnVuY3Rpb24gZ2VuZXJhckxpbmsoKSB7CiAgICBzZXRMb2FkaW5nKHRydWUpCiAgICBzZXRFcnJvcignJykKCiAgICBjb25zdCB7IGRhdGE6IHsgdXNlciB9IH0gPSBhd2FpdCBzdXBhYmFzZS5hdXRoLmdldFVzZXIoKQogICAgaWYgKCF1c2VyKSB7CiAgICAgIHNldEVycm9yKCdObyBzZSBwdWRvIHZlcmlmaWNhciB0dSBzZXNpb24uIFZ1ZWx2ZSBhIGVudHJhciBlIGludGVudGEgZGUgbnVldm8uJykKICAgICAgc2V0TG9hZGluZyhmYWxzZSkKICAgICAgcmV0dXJuCiAgICB9CgogICAgLy8gRG9ibGUgY2hlcXVlbyBhbnRlcyBkZSBpbnNlcnRhcjogc2kgZW50cmUgZWwgbW9udGFqZSB5IGVzdGUgY2xpYwogICAgLy8gYXBhcmVjaW8gdW4gbGluayB2aWdlbnRlIChlai4gZ2VuZXJhZG8gZGVzZGUgZWwgRGFzaGJvYXJkKSwgc2UKICAgIC8vIHJldXNhIGVuIHZleiBkZSBjcmVhciBvdHJvLgogICAgY29uc3QgdmlnZW50ZSA9IGF3YWl0IGJ1c2NhclZpZ2VudGUoKQogICAgaWYgKHZpZ2VudGUpIHsKICAgICAgc2V0TGluayhgJHt3aW5kb3cubG9jYXRpb24ub3JpZ2lufS92ZXQ/dG9rZW49JHt2aWdlbnRlLnRva2VufWApCiAgICAgIHNldEV4cGlyYSh2aWdlbnRlLmV4cGlyYV9lbikKICAgICAgc2V0TG9hZGluZyhmYWxzZSkKICAgICAgcmV0dXJuCiAgICB9CgogICAgY29uc3QgeyBkYXRhIH0gPSBhd2FpdCBzdXBhYmFzZQogICAgICAuZnJvbSgnbGlua3NfdmV0ZXJpbmFyaW8nKQogICAgICAuaW5zZXJ0KHsgbWFzY290YV9pZDogbWFzY290YUlkLCB1c2VyX2lkOiB1c2VyLmlkIH0pCiAgICAgIC5zZWxlY3QoJ3Rva2VuLCBleHBpcmFfZW4nKQogICAgICAuc2luZ2xlKCkKCiAgICBpZiAoZGF0YSAmJiBkYXRhLnRva2VuKSB7CiAgICAgIHNldExpbmsoYCR7d2luZG93LmxvY2F0aW9uLm9yaWdpbn0vdmV0P3Rva2VuPSR7ZGF0YS50b2tlbn1gKQogICAgICBzZXRFeHBpcmEoZGF0YS5leHBpcmFfZW4gYXMgc3RyaW5nKQogICAgfSBlbHNlIHsKICAgICAgc2V0RXJyb3IoJ05vIHNlIHB1ZG8gZ2VuZXJhciBlbCBsaW5rLiBSZXZpc2EgdHUgY29uZXhpb24gZSBpbnRlbnRhIGRlIG51ZXZvLicpCiAgICB9CiAgICBzZXRMb2FkaW5nKGZhbHNlKQogIH0KCiAgYXN5bmMgZnVuY3Rpb24gY29waWFyKCkgewogICAgdHJ5IHsKICAgICAgYXdhaXQgbmF2aWdhdG9yLmNsaXBib2FyZC53cml0ZVRleHQobGluaykKICAgICAgc2V0Q29waWFkbyh0cnVlKQogICAgICBzZXRUaW1lb3V0KCgpID0+IHNldENvcGlhZG8oZmFsc2UpLCAyMDAwKQogICAgfSBjYXRjaCB7CiAgICAgIC8vIFNpIGVsIG5hdmVnYWRvciBibG9xdWVhIGVsIHBvcnRhcGFwZWxlcywgZWwgbGluayBpZ3VhbCBlc3RhCiAgICAgIC8vIHZpc2libGUgYXJyaWJhIGNvbiBsYSBjbGFzZSAuY29waWFibGUgcGFyYSBjb3BpYXJsbyBhIG1hbm8uCiAgICAgIHNldEVycm9yKCdUdSBuYXZlZ2Fkb3Igbm8gcGVybWl0aW8gY29waWFyLiBTZWxlY2Npb25hIGVsIGxpbmsgZGUgYXJyaWJhIHkgY29waWFsbyBhIG1hbm8uJykKICAgIH0KICB9CgogIHJldHVybiAoCiAgICA8ZGl2IGNsYXNzTmFtZT0ibXgtNCBtYi00IGJnLVsjRkZGQ0Y4XSByb3VuZGVkLTJ4bCBib3JkZXIgYm9yZGVyLVsjRUVFMkQ0XSBvdmVyZmxvdy1oaWRkZW4iPgogICAgICA8ZGl2IGNsYXNzTmFtZT0icHgtNCBweS0zIGJvcmRlci1iIGJvcmRlci1bI0VFRTJENF0iPgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMiBtYi0xIj4KICAgICAgICAgIDxpbWcgc3JjPSIvY2hpcXVpL2NoaXF1aV9kb2N0b3IucG5nIiBhbHQ9IiIgY2xhc3NOYW1lPSJ3LTcgaC03IG9iamVjdC1jb250YWluIiAvPgogICAgICAgICAgPGgyIGNsYXNzTmFtZT0iZm9udC1ib2xkIHRleHQtc20iPkNvbXBhcnRlIGVsIGhpc3RvcmlhbCBjb24gdHUgdmV0PC9oMj4KICAgICAgICA8L2Rpdj4KICAgICAgICA8cCBjbGFzc05hbWU9InRleHQteHMgdGV4dC1bIzhBNzU2MF0gbXQtMC41Ij5DSElRVUkgcmVjb21pZW5kYSBlbnZpYXJsbyBhbnRlcyBvIGR1cmFudGUgbGEgY29uc3VsdGEsIHBhcmEgcXVlIHR1IHZldCBsbGVndWUgY29uIGNvbnRleHRvLjwvcD4KICAgICAgPC9kaXY+CiAgICAgIDxkaXYgY2xhc3NOYW1lPSJwLTQiPgogICAgICAgIHtidXNjYW5kbyA/ICgKICAgICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC14cyB0ZXh0LVsjOEE3NTYwXSB0ZXh0LWNlbnRlciBweS0yIj5DYXJnYW5kby4uLjwvcD4KICAgICAgICApIDogIWxpbmsgPyAoCiAgICAgICAgICA8YnV0dG9uIG9uQ2xpY2s9e2dlbmVyYXJMaW5rfSBkaXNhYmxlZD17bG9hZGluZ30KICAgICAgICAgICAgY2xhc3NOYW1lPSJ3LWZ1bGwgYmctWyM0QUFCREJdIHRleHQtd2hpdGUgZm9udC1ib2xkIHB5LTMgcm91bmRlZC14bCB0ZXh0LXNtIGRpc2FibGVkOm9wYWNpdHktNTAiPgogICAgICAgICAgICB7bG9hZGluZyA/ICdHZW5lcmFuZG8uLi4nIDogJ/CflJcgR2VuZXJhciBsaW5rIHBhcmEgZWwgdmV0J30KICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICkgOiAoCiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ic3BhY2UteS0zIj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImNvcGlhYmxlIGJnLVsjRkJFQUQ5XSByb3VuZGVkLXhsIHAtMyB0ZXh0LXhzIHRleHQtWyM4QTc1NjBdIGJyZWFrLWFsbCBib3JkZXIgYm9yZGVyLVsjRUVFMkQ0XSI+CiAgICAgICAgICAgICAge2xpbmt9CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8YnV0dG9uIG9uQ2xpY2s9e2NvcGlhcn0KICAgICAgICAgICAgICBjbGFzc05hbWU9InctZnVsbCBiZy1bIzRDQUY3RF0gdGV4dC1bIzBhMjQxOF0gZm9udC1ib2xkIHB5LTMgcm91bmRlZC14bCB0ZXh0LXNtIj4KICAgICAgICAgICAgICB7Y29waWFkbyA/ICfinIUgwqFDb3BpYWRvIScgOiAn8J+TiyBDb3BpYXIgbGluayd9CiAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQteHMgdGV4dC1bIzhBNzU2MF0gdGV4dC1jZW50ZXIiPkVsIHZldGVyaW5hcmlvIHB1ZWRlIHZlciBlbCBoaXN0b3JpYWwgc2luIGNyZWFyIGN1ZW50YTwvcD4KICAgICAgICAgICAge2V4cGlyYSAmJiAoCiAgICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LVsxMXB4XSB0ZXh0LVsjQ0Q3NDIxXSB0ZXh0LWNlbnRlciBmb250LXNlbWlib2xkIj4KICAgICAgICAgICAgICAgIEVzdGUgbGluayBmdW5jaW9uYSBoYXN0YSBlbCB7Zm10RXhwaXJhKGV4cGlyYSl9LiBEZXNwdWVzIHB1ZWRlcyBnZW5lcmFyIHVubyBudWV2by4KICAgICAgICAgICAgICA8L3A+CiAgICAgICAgICAgICl9CiAgICAgICAgICA8L2Rpdj4KICAgICAgICApfQogICAgICAgIHtlcnJvciAmJiAoCiAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtWzExcHhdIHRleHQtWyNFMDUyNTJdIHRleHQtY2VudGVyIG10LTIiPntlcnJvcn08L3A+CiAgICAgICAgKX0KICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICApCn0K';

function abortar(motivo) {
  console.log('');
  console.log('ABORTADO: ' + motivo);
  console.log('No se modifico ningun archivo. Avisale a Claude lo que dice este mensaje.');
  process.exit(1);
}

const destino = path.join(process.cwd(), RUTA);

if (!fs.existsSync(destino)) {
  abortar('no se encontro ' + RUTA + '. Corre el script desde la raiz del proyecto.');
}

const actual = fs.readFileSync(destino, 'utf8');

// --- Verificacion 1: debe ser la version vieja, no una ya arreglada
if (actual.includes('buscarVigente')) {
  abortar('el archivo ya tiene la logica nueva. Parece que este script ya se corrio.');
}

// --- Verificacion 2: senales de que es el LinkVet que esperamos
const SENALES = [
  "from('links_veterinario')",
  'export default function LinkVet',
  'mascotaId',
];
for (const s of SENALES) {
  if (!actual.includes(s)) {
    abortar('el archivo actual no contiene [' + s + ']. No es el LinkVet que esperaba.');
  }
}
console.log('  OK el archivo actual es la version vieja de LinkVet');

// --- Escritura
const nuevo = Buffer.from(LINKVET_B64, 'base64').toString('utf8');

// --- Verificacion 3: el contenido nuevo debe traer lo prometido
const REQUERIDOS = [
  'buscarVigente',
  ".gt('expira_en', ahora)",
  'fmtExpira',
  'export default function LinkVet',
];
for (const r of REQUERIDOS) {
  if (!nuevo.includes(r)) {
    abortar('el contenido nuevo no incluye [' + r + ']. Script corrupto, no se escribio nada.');
  }
}

const carpeta = path.dirname(destino);
if (!fs.existsSync(carpeta)) {
  fs.mkdirSync(carpeta, { recursive: true });
}
fs.writeFileSync(destino, nuevo, 'utf8');

console.log('');
console.log('OK: ' + RUTA);
console.log('');
console.log('Listo. LinkVet ya no crea una fila nueva en cada toque.');
