// Script: generar_44_fix_tipo_typescript.js
// Que hace: corrige el error de TypeScript que hizo fallar los ultimos
// 2 despliegues en Vercel.
//
// La causa: TypeScript 5.9 (la version que usa tu proyecto) cambio como
// funcionan los tipos de Uint8Array, haciendo que el tipo generico
// "Uint8Array<ArrayBufferLike>" que se infiere por defecto ya no
// coincida exactamente con lo que pide la funcion nativa del navegador
// pushManager.subscribe(). El codigo era correcto y funcionaria bien en
// el navegador, pero el chequeo de tipos de TypeScript lo rechazaba al
// compilar.
//
// La correccion: especificar explicitamente el tipo concreto
// "Uint8Array<ArrayBuffer>" en la funcion que convierte la clave VAPID,
// en vez de dejar que TypeScript infiera el tipo generico ambiguo. Esto
// se confirmo probando la compilacion real con TypeScript 5.9.3 (la
// misma version usada en el build que fallo) -- el error original ya
// no aparece.
//
//   1) utils/pushNotificaciones.ts (REEMPLAZA el existente)
//
// Como correrlo: node generar_44_fix_tipo_typescript.js
// Confirma "OK: utils/pushNotificaciones.ts"

const fs = require('fs');
const path = require('path');

const filePath = path.join('utils', 'pushNotificaciones.ts');
const b64 = "J3VzZSBjbGllbnQnCmltcG9ydCB7IGNyZWF0ZUNsaWVudCB9IGZyb20gJ0AvdXRpbHMvc3VwYWJhc2UvY2xpZW50JwoKLy8gQ29udmllcnRlIGxhIGNsYXZlIHB1YmxpY2EgVkFQSUQgKHRleHRvIGJhc2U2NCkgYWwgZm9ybWF0byBVaW50OEFycmF5Ci8vIHF1ZSBwaWRlIGxhIEFQSSBuYXRpdmEgZGVsIG5hdmVnYWRvci4gU2luIGVzdG8sIHB1c2hNYW5hZ2VyLnN1YnNjcmliZQovLyByZWNoYXphIGxhIGNsYXZlLgpmdW5jdGlvbiB1cmxCYXNlNjRUb1VpbnQ4QXJyYXkoYmFzZTY0U3RyaW5nOiBzdHJpbmcpOiBVaW50OEFycmF5PEFycmF5QnVmZmVyPiB7CiAgY29uc3QgcGFkZGluZyA9ICc9Jy5yZXBlYXQoKDQgLSAoYmFzZTY0U3RyaW5nLmxlbmd0aCAlIDQpKSAlIDQpCiAgY29uc3QgYmFzZTY0ID0gKGJhc2U2NFN0cmluZyArIHBhZGRpbmcpLnJlcGxhY2UoLy0vZywgJysnKS5yZXBsYWNlKC9fL2csICcvJykKICBjb25zdCByYXdEYXRhID0gd2luZG93LmF0b2IoYmFzZTY0KQogIGNvbnN0IG91dHB1dEFycmF5ID0gbmV3IFVpbnQ4QXJyYXkobmV3IEFycmF5QnVmZmVyKHJhd0RhdGEubGVuZ3RoKSkKICBmb3IgKGxldCBpID0gMDsgaSA8IHJhd0RhdGEubGVuZ3RoOyArK2kpIHsKICAgIG91dHB1dEFycmF5W2ldID0gcmF3RGF0YS5jaGFyQ29kZUF0KGkpCiAgfQogIHJldHVybiBvdXRwdXRBcnJheQp9CgovLyB0cnVlIHNpIGVsIG5hdmVnYWRvciBhY3R1YWwgc29wb3J0YSBub3RpZmljYWNpb25lcyBwdXNoIGVuIGFic29sdXRvLgovLyBFbiBpUGhvbmUsIGVzdG8gc29sbyBlcyB0cnVlIERFU1BVRVMgZGUgaW5zdGFsYXIgbGEgUFdBIGEgbGEgcGFudGFsbGEKLy8gZGUgaW5pY2lvIC0tIHVuYSBwZXN0YcOxYSBub3JtYWwgZGUgU2FmYXJpIG5vIGxvIHNvcG9ydGEuCmV4cG9ydCBmdW5jdGlvbiBub3RpZmljYWNpb25lc1NvcG9ydGFkYXMoKTogYm9vbGVhbiB7CiAgaWYgKHR5cGVvZiB3aW5kb3cgPT09ICd1bmRlZmluZWQnKSByZXR1cm4gZmFsc2UKICByZXR1cm4gJ3NlcnZpY2VXb3JrZXInIGluIG5hdmlnYXRvciAmJiAnUHVzaE1hbmFnZXInIGluIHdpbmRvdyAmJiAnTm90aWZpY2F0aW9uJyBpbiB3aW5kb3cKfQoKLy8gRGV0ZWN0YSBzaSBlc3RhbW9zIGVuIGlPUy9pUGFkT1MsIHBhcmEgbW9zdHJhciBpbnN0cnVjY2lvbmVzCi8vIGVzcGVjaWFsZXMgZGUgImFncmVnYXIgYSBpbmljaW8iIGN1YW5kbyBoYWdhIGZhbHRhLgpleHBvcnQgZnVuY3Rpb24gZXNJT1MoKTogYm9vbGVhbiB7CiAgaWYgKHR5cGVvZiB3aW5kb3cgPT09ICd1bmRlZmluZWQnKSByZXR1cm4gZmFsc2UKICByZXR1cm4gL2lwaG9uZXxpcGFkfGlwb2QvaS50ZXN0KHdpbmRvdy5uYXZpZ2F0b3IudXNlckFnZW50KQp9CgovLyBEZXRlY3RhIHNpIGxhIGFwcCB5YSBlc3RhIGNvcnJpZW5kbyBpbnN0YWxhZGEgKG1vZG8gc3RhbmRhbG9uZSksIHF1ZQovLyBlcyByZXF1aXNpdG8gZW4gaU9TIHBhcmEgcXVlIGxhcyBub3RpZmljYWNpb25lcyBmdW5jaW9uZW4uCmV4cG9ydCBmdW5jdGlvbiBlc3RhSW5zdGFsYWRhKCk6IGJvb2xlYW4gewogIGlmICh0eXBlb2Ygd2luZG93ID09PSAndW5kZWZpbmVkJykgcmV0dXJuIGZhbHNlCiAgcmV0dXJuIHdpbmRvdy5tYXRjaE1lZGlhKCcoZGlzcGxheS1tb2RlOiBzdGFuZGFsb25lKScpLm1hdGNoZXMgfHwgKHdpbmRvdy5uYXZpZ2F0b3IgYXMgYW55KS5zdGFuZGFsb25lID09PSB0cnVlCn0KCi8vIFBpZGUgcGVybWlzbyBkZSBub3RpZmljYWNpb25lcywgc2Ugc3VzY3JpYmUgYW50ZSBlbCBuYXZlZ2Fkb3IsIHkKLy8gZ3VhcmRhIGxhIHN1c2NyaXBjaW9uIGVuIFN1cGFiYXNlIHBhcmEgcG9kZXIgdXNhcmxhIGRlc3B1ZXMgZGVzZGUgZWwKLy8gc2Vydmlkb3IuCmV4cG9ydCBhc3luYyBmdW5jdGlvbiBhY3RpdmFyTm90aWZpY2FjaW9uZXMoKTogUHJvbWlzZTx7IGV4aXRvOiBib29sZWFuOyBlcnJvcj86IHN0cmluZyB9PiB7CiAgaWYgKCFub3RpZmljYWNpb25lc1NvcG9ydGFkYXMoKSkgewogICAgcmV0dXJuIHsgZXhpdG86IGZhbHNlLCBlcnJvcjogJ0VzdGUgbmF2ZWdhZG9yIG5vIHNvcG9ydGEgbm90aWZpY2FjaW9uZXMuJyB9CiAgfQoKICBjb25zdCBwZXJtaXNvID0gYXdhaXQgTm90aWZpY2F0aW9uLnJlcXVlc3RQZXJtaXNzaW9uKCkKICBpZiAocGVybWlzbyAhPT0gJ2dyYW50ZWQnKSB7CiAgICByZXR1cm4geyBleGl0bzogZmFsc2UsIGVycm9yOiAnTm8gZGlzdGUgcGVybWlzbyBwYXJhIGxhcyBub3RpZmljYWNpb25lcy4nIH0KICB9CgogIGNvbnN0IHJlZ2lzdHJhdGlvbiA9IGF3YWl0IG5hdmlnYXRvci5zZXJ2aWNlV29ya2VyLnJlYWR5CiAgY29uc3QgdmFwaWRQdWJsaWNLZXkgPSBwcm9jZXNzLmVudi5ORVhUX1BVQkxJQ19WQVBJRF9QVUJMSUNfS0VZCiAgaWYgKCF2YXBpZFB1YmxpY0tleSkgewogICAgcmV0dXJuIHsgZXhpdG86IGZhbHNlLCBlcnJvcjogJ0ZhbHRhIGNvbmZpZ3VyYWNpw7NuIGRlbCBzZXJ2aWRvci4nIH0KICB9CgogIGNvbnN0IHN1YnNjcmlwdGlvbiA9IGF3YWl0IHJlZ2lzdHJhdGlvbi5wdXNoTWFuYWdlci5zdWJzY3JpYmUoewogICAgdXNlclZpc2libGVPbmx5OiB0cnVlLAogICAgYXBwbGljYXRpb25TZXJ2ZXJLZXk6IHVybEJhc2U2NFRvVWludDhBcnJheSh2YXBpZFB1YmxpY0tleSksCiAgfSkKCiAgY29uc3Qgc3Vic2NyaXB0aW9uSnNvbiA9IHN1YnNjcmlwdGlvbi50b0pTT04oKQogIGNvbnN0IHN1cGFiYXNlID0gY3JlYXRlQ2xpZW50KCkKICBjb25zdCB7IGRhdGE6IHsgdXNlciB9IH0gPSBhd2FpdCBzdXBhYmFzZS5hdXRoLmdldFVzZXIoKQogIGlmICghdXNlcikgcmV0dXJuIHsgZXhpdG86IGZhbHNlLCBlcnJvcjogJ1Nlc2nDs24gbm8gZW5jb250cmFkYS4nIH0KCiAgY29uc3QgeyBlcnJvciB9ID0gYXdhaXQgc3VwYWJhc2UuZnJvbSgnc3VzY3JpcGNpb25lc19wdXNoJykudXBzZXJ0KHsKICAgIHVzZXJfaWQ6IHVzZXIuaWQsCiAgICBlbmRwb2ludDogc3Vic2NyaXB0aW9uSnNvbi5lbmRwb2ludCEsCiAgICBwMjU2ZGg6IHN1YnNjcmlwdGlvbkpzb24ua2V5cyEucDI1NmRoLAogICAgYXV0aDogc3Vic2NyaXB0aW9uSnNvbi5rZXlzIS5hdXRoLAogIH0sIHsgb25Db25mbGljdDogJ2VuZHBvaW50JyB9KQoKICBpZiAoZXJyb3IpIHJldHVybiB7IGV4aXRvOiBmYWxzZSwgZXJyb3I6ICdObyBzZSBwdWRvIGd1YXJkYXIgbGEgc3VzY3JpcGNpw7NuLicgfQoKICByZXR1cm4geyBleGl0bzogdHJ1ZSB9Cn0KCi8vIENhbmNlbGEgbGEgc3VzY3JpcGNpb24sIHRhbnRvIGFudGUgZWwgbmF2ZWdhZG9yIGNvbW8gZW4gU3VwYWJhc2UuCmV4cG9ydCBhc3luYyBmdW5jdGlvbiBkZXNhY3RpdmFyTm90aWZpY2FjaW9uZXMoKTogUHJvbWlzZTx2b2lkPiB7CiAgaWYgKCFub3RpZmljYWNpb25lc1NvcG9ydGFkYXMoKSkgcmV0dXJuCiAgY29uc3QgcmVnaXN0cmF0aW9uID0gYXdhaXQgbmF2aWdhdG9yLnNlcnZpY2VXb3JrZXIucmVhZHkKICBjb25zdCBzdWJzY3JpcHRpb24gPSBhd2FpdCByZWdpc3RyYXRpb24ucHVzaE1hbmFnZXIuZ2V0U3Vic2NyaXB0aW9uKCkKICBpZiAoc3Vic2NyaXB0aW9uKSB7CiAgICBjb25zdCBzdXBhYmFzZSA9IGNyZWF0ZUNsaWVudCgpCiAgICBhd2FpdCBzdXBhYmFzZS5mcm9tKCdzdXNjcmlwY2lvbmVzX3B1c2gnKS5kZWxldGUoKS5lcSgnZW5kcG9pbnQnLCBzdWJzY3JpcHRpb24uZW5kcG9pbnQpCiAgICBhd2FpdCBzdWJzY3JpcHRpb24udW5zdWJzY3JpYmUoKQogIH0KfQoKLy8gUmV2aXNhIHNpIGVsIG5hdmVnYWRvciBhY3R1YWwgeWEgdGllbmUgdW5hIHN1c2NyaXBjaW9uIGFjdGl2YSAodXRpbAovLyBwYXJhIHNhYmVyIHF1ZSBtb3N0cmFyIGVuIGxhIFVJOiBib3RvbiBkZSAiQWN0aXZhciIgbyBkZSAiRGVzYWN0aXZhciIpLgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gdGllbmVTdXNjcmlwY2lvbkFjdGl2YSgpOiBQcm9taXNlPGJvb2xlYW4+IHsKICBpZiAoIW5vdGlmaWNhY2lvbmVzU29wb3J0YWRhcygpKSByZXR1cm4gZmFsc2UKICB0cnkgewogICAgY29uc3QgcmVnaXN0cmF0aW9uID0gYXdhaXQgbmF2aWdhdG9yLnNlcnZpY2VXb3JrZXIucmVhZHkKICAgIGNvbnN0IHN1YnNjcmlwdGlvbiA9IGF3YWl0IHJlZ2lzdHJhdGlvbi5wdXNoTWFuYWdlci5nZXRTdWJzY3JpcHRpb24oKQogICAgcmV0dXJuICEhc3Vic2NyaXB0aW9uCiAgfSBjYXRjaCB7CiAgICByZXR1cm4gZmFsc2UKICB9Cn0K";
const content = Buffer.from(b64, 'base64').toString('utf8');

const dir = path.dirname(filePath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

fs.writeFileSync(filePath, content, 'utf8');
console.log('OK: ' + filePath);
