const fs = require('fs');
const path = require('path');

// ============================================================
// generar_349_aviso_visita_veterinaria.js
// ============================================================
// Crea app/api/cron/visitas/route.ts: aviso push la noche antes de una
// hora con el veterinario.
//
// POR QUE UNA RUTA NUEVA Y NO SUMARLA A LAS EXISTENTES
// Las dos rutas actuales tienen cada una su proposito y su hora. Meter
// una tercera logica adentro las volveria dificiles de entender y de
// desactivar por separado. Ademas, esta se llama igual que las otras
// (cada hora, con el mismo CRON_SECRET), asi que el costo de tenerla
// aparte es solo un job mas en cron-job.org.
//
// COMO FUNCIONA
//  - Se ejecuta cada hora, pero solo actua a las 19:00 hora Chile.
//  - Busca las visitas agendadas para MAÑANA.
//  - Filtra a quienes tienen notificaciones activas: una hora agendada
//    no autoriza a escribirle a alguien que apago los avisos.
//  - Manda una notificacion por visita, con nombre, hora y motivo.
//
// La consulta parte por FECHA (pocas filas) en vez de recorrer usuario
// por usuario: la mayoria de los dias no habra ninguna visita, y asi la
// ruta termina de inmediato sin costo.
//
// FALTA UN PASO MANUAL: agregar el job en cron-job.org. Sin eso, la
// ruta existe pero nadie la llama nunca. Las instrucciones van aparte.
//
// Este script solo CREA un archivo nuevo. No modifica nada existente.
// ============================================================

const RUTA = 'app/api/cron/visitas/route.ts';
const VISITAS_B64 = 'aW1wb3J0IHsgTmV4dFJlc3BvbnNlIH0gZnJvbSAnbmV4dC9zZXJ2ZXInCmltcG9ydCB3ZWJwdXNoIGZyb20gJ3dlYi1wdXNoJwppbXBvcnQgeyBjcmVhdGVDbGllbnQgfSBmcm9tICdAc3VwYWJhc2Uvc3VwYWJhc2UtanMnCgovLyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KLy8gQVZJU08gREUgVklTSVRBIFZFVEVSSU5BUklBIOKAlCBlbCBkw61hIGFudGVzCi8vID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQovLyBSdXRhIHNlcGFyYWRhIGRlIGxhcyBvdHJhcyBkb3MgKHJlY29yZGF0b3JpbyBkaWFyaW8geSByYWNoYSBlbgovLyByaWVzZ28pLiBMYSBsbGFtYSBlbCBtaXNtbyBzZXJ2aWNpbyBleHRlcm5vIChjcm9uLWpvYi5vcmcpIFVOQSBWRVoKLy8gUE9SIEhPUkEsIHBlcm8gc29sbyBhY3TDumEgYSBsYXMgMTk6MDAgaG9yYSBDaGlsZSDigJQgbGFzIGRlbcOhcyBob3JhcwovLyBubyBoYWNlbiBuYWRhLiBFc2UgcGF0csOzbiBlcyBlbCBtaXNtbyBkZSByYWNoYS1yaWVzZ286IHNpbXBsaWZpY2EgbGEKLy8gY29uZmlndXJhY2nDs24gcG9ycXVlIHRvZGFzIGxhcyBydXRhcyBzZSBsbGFtYW4gaWd1YWwsIGNhZGEgaG9yYS4KLy8KLy8gUE9SIFFVw4kgRUwgRMONQSBBTlRFUyBZIE5PIEVMIE1JU01PIETDjUEKLy8gVW5hIGhvcmEgY29uIGVsIHZldGVyaW5hcmlvIGNhc2kgc2llbXByZSBuZWNlc2l0YSBwcmVwYXJhY2nDs246Ci8vIGF5dW5vIHBhcmEgZXjDoW1lbmVzLCBlbmNvbnRyYXIgZWwgdHJhbnNwb3J0w61uLCBwZWRpciBwZXJtaXNvIGVuIGVsCi8vIHRyYWJham8sIGNhcmdhciBlbCBjYXJuZXQuIEF2aXNhciBsYSBtYcOxYW5hIG1pc21hIGxsZWdhIHRhcmRlIHBhcmEKLy8gdG9kbyBlc28uCi8vCi8vIFBPUiBRVcOJIEEgTEFTIDE5OjAwCi8vIEVzIGxhIGhvcmEgZW4gcXVlIGxhIG1heW9yw61hIHlhIGVzdMOhIGVuIHN1IGNhc2EgeSB0b2RhdsOtYSBwdWVkZQovLyBvcmdhbml6YXIgZWwgZMOtYSBzaWd1aWVudGUuIE3DoXMgdGFyZGUgKDIyOjAwLCBjb21vIGxhIHJhY2hhKSBzZXLDrWEKLy8gY2FzaSBsbyBtaXNtbyBxdWUgYXZpc2FyIGVuIGxhIG1hw7FhbmEuCi8vCi8vIFVOQSBTT0xBIE5PVElGSUNBQ0nDk04gUE9SIFZJU0lUQSwgbm8gcG9yIG1hc2NvdGE6IHNpIGFsZ3VpZW4gbGxldmEKLy8gZG9zIGFuaW1hbGVzIGVsIG1pc21vIGTDrWEsIHJlY2liZSBkb3MgYXZpc29zLCBxdWUgZXMgbG8gY29ycmVjdG8g4oCUCi8vIHNvbiBkb3MgaG9yYXMgZGlzdGludGFzLgovLwovLyBQcm90ZWdpZGEgY29uIENST05fU0VDUkVULCBpZ3VhbCBxdWUgbGFzIG90cmFzIGRvcyBydXRhcy4KCmZ1bmN0aW9uIGNyZWFyQ2xpZW50ZUFkbWluKCkgewogIHJldHVybiBjcmVhdGVDbGllbnQoCiAgICBwcm9jZXNzLmVudi5ORVhUX1BVQkxJQ19TVVBBQkFTRV9VUkwhLAogICAgcHJvY2Vzcy5lbnYuU1VQQUJBU0VfU0VSVklDRV9ST0xFX0tFWSEKICApCn0KCmZ1bmN0aW9uIGhvcmFBY3R1YWxDaGlsZSgpOiBzdHJpbmcgewogIGNvbnN0IGFob3JhID0gbmV3IERhdGUoKQogIGNvbnN0IGhvcmFDaGlsZSA9IG5ldyBJbnRsLkRhdGVUaW1lRm9ybWF0KCdlcy1DTCcsIHsKICAgIHRpbWVab25lOiAnQW1lcmljYS9TYW50aWFnbycsCiAgICBob3VyOiAnMi1kaWdpdCcsCiAgICBob3VyMTI6IGZhbHNlLAogIH0pLmZvcm1hdChhaG9yYSkKICBjb25zdCBob3JhID0gaG9yYUNoaWxlLnJlcGxhY2UoL1teMC05XS9nLCAnJykucGFkU3RhcnQoMiwgJzAnKS5zbGljZSgwLCAyKQogIHJldHVybiBgJHtob3JhfTowMGAKfQoKZnVuY3Rpb24gZmVjaGFDaGlsZShkYXRlOiBEYXRlID0gbmV3IERhdGUoKSk6IHN0cmluZyB7CiAgcmV0dXJuIG5ldyBJbnRsLkRhdGVUaW1lRm9ybWF0KCdlbi1DQScsIHsgdGltZVpvbmU6ICdBbWVyaWNhL1NhbnRpYWdvJyB9KS5mb3JtYXQoZGF0ZSkKfQoKY29uc3QgSE9SQV9FTlZJTyA9ICcxOTowMCcKCi8vIFRleHRvIHNlZ8O6biBlbCB0aXBvIGRlIHZpc2l0YS4gRWwgbW90aXZvLCBzaSBleGlzdGUsIGRpY2UgbcOhcyBxdWUgZWwKLy8gdGlwbywgYXPDrSBxdWUgdGllbmUgcHJpb3JpZGFkLgpmdW5jdGlvbiBkZXNjcmlwY2lvblZpc2l0YSh0aXBvOiBzdHJpbmcgfCBudWxsLCBtb3Rpdm86IHN0cmluZyB8IG51bGwpOiBzdHJpbmcgewogIGlmIChtb3Rpdm8gJiYgbW90aXZvLnRyaW0oKSkgcmV0dXJuIG1vdGl2by50cmltKCkKICBpZiAodGlwbyA9PT0gJ2V4YW1lbmVzJykgcmV0dXJuICdleMOhbWVuZXMnCiAgaWYgKHRpcG8gPT09ICdlbmZlcm1lZGFkJykgcmV0dXJuICdjb250cm9sIHBvciBlbmZlcm1lZGFkJwogIGlmICh0aXBvID09PSAndHJhdGFtaWVudG8nKSByZXR1cm4gJ3RyYXRhbWllbnRvJwogIHJldHVybiAnY29udHJvbCBkZSBydXRpbmEnCn0KCmV4cG9ydCBhc3luYyBmdW5jdGlvbiBHRVQocmVxdWVzdDogUmVxdWVzdCkgewogIGNvbnN0IGF1dGhIZWFkZXIgPSByZXF1ZXN0LmhlYWRlcnMuZ2V0KCdhdXRob3JpemF0aW9uJykKICBpZiAoYXV0aEhlYWRlciAhPT0gYEJlYXJlciAke3Byb2Nlc3MuZW52LkNST05fU0VDUkVUfWApIHsKICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNvbih7IGVycm9yOiAnTm8gYXV0b3JpemFkbycgfSwgeyBzdGF0dXM6IDQwMSB9KQogIH0KCiAgY29uc3QgaG9yYUFjdHVhbCA9IGhvcmFBY3R1YWxDaGlsZSgpCiAgaWYgKGhvcmFBY3R1YWwgIT09IEhPUkFfRU5WSU8pIHsKICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNvbih7IG1lbnNhamU6ICdObyBlcyBsYSBob3JhIGRlIGVudsOtbycsIGhvcmE6IGhvcmFBY3R1YWwgfSkKICB9CgogIHdlYnB1c2guc2V0VmFwaWREZXRhaWxzKAogICAgJ21haWx0bzpjb250YWN0b0BjaGlxdWktYXBwLmNsJywKICAgIHByb2Nlc3MuZW52Lk5FWFRfUFVCTElDX1ZBUElEX1BVQkxJQ19LRVkhLAogICAgcHJvY2Vzcy5lbnYuVkFQSURfUFJJVkFURV9LRVkhCiAgKQoKICBjb25zdCBzdXBhYmFzZSA9IGNyZWFyQ2xpZW50ZUFkbWluKCkKCiAgLy8gTWHDsWFuYSwgZW4gaG9yYSBkZSBDaGlsZS4gU2UgY29uc3RydXllIGEgbWVkaW9kw61hIHBhcmEgcXVlIGxvcwogIC8vIGNhbWJpb3MgZGUgaG9yYXJpbyBkZSB2ZXJhbm8gbm8gY29ycmFuIGVsIGTDrWEuCiAgY29uc3QgbWFuaWFuYURhdGUgPSBuZXcgRGF0ZSgpCiAgbWFuaWFuYURhdGUuc2V0RGF0ZShtYW5pYW5hRGF0ZS5nZXREYXRlKCkgKyAxKQogIGNvbnN0IG1hbmlhbmEgPSBmZWNoYUNoaWxlKG1hbmlhbmFEYXRlKQoKICAvLyBQYXNvIDE6IHRvZGFzIGxhcyB2aXNpdGFzIGFnZW5kYWRhcyBwYXJhIG1hw7FhbmEuIFNlIGNvbnN1bHRhIHBvcgogIC8vIGZlY2hhIHByaW1lcm8gKHNvbiBwb2NhcyBmaWxhcykgZW4gdmV6IGRlIHJlY29ycmVyIHVzdWFyaW8gcG9yCiAgLy8gdXN1YXJpbzogbGEgbWF5b3LDrWEgZGUgbG9zIGTDrWFzIG5vIGhhYnLDoSBuaW5ndW5hLgogIGNvbnN0IHsgZGF0YTogdmlzaXRhcyB9ID0gYXdhaXQgc3VwYWJhc2UKICAgIC5mcm9tKCd2aXNpdGFzX3ZldGVyaW5hcmlhcycpCiAgICAuc2VsZWN0KCdpZCwgdXNlcl9pZCwgbWFzY290YV9pZCwgZmVjaGEsIGhvcmEsIHRpcG8sIG1vdGl2bywgdmV0ZXJpbmFyaW8nKQogICAgLmVxKCdmZWNoYScsIG1hbmlhbmEpCgogIGlmICghdmlzaXRhcyB8fCB2aXNpdGFzLmxlbmd0aCA9PT0gMCkgewogICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgbWVuc2FqZTogJ1NpbiB2aXNpdGFzIHBhcmEgbWHDsWFuYScsIGZlY2hhOiBtYW5pYW5hLCBlbnZpYWRvczogMCB9KQogIH0KCiAgLy8gUGFzbyAyOiBkZSBlc29zIHVzdWFyaW9zLCBzb2xvIGxvcyBxdWUgdGllbmVuIG5vdGlmaWNhY2lvbmVzCiAgLy8gYWN0aXZhcy4gVW5hIHZpc2l0YSBhZ2VuZGFkYSBubyBhdXRvcml6YSBhIGVzY3JpYmlybGUgYSBhbGd1aWVuIHF1ZQogIC8vIGFwYWfDsyBsb3MgYXZpc29zLgogIGNvbnN0IGlkc1VzdWFyaW9zID0gQXJyYXkuZnJvbShuZXcgU2V0KHZpc2l0YXMubWFwKHYgPT4gdi51c2VyX2lkKS5maWx0ZXIoQm9vbGVhbikpKQogIGNvbnN0IHsgZGF0YTogYWN0aXZvcyB9ID0gYXdhaXQgc3VwYWJhc2UKICAgIC5mcm9tKCdwcmVmZXJlbmNpYXNfdXN1YXJpbycpCiAgICAuc2VsZWN0KCd1c2VyX2lkJykKICAgIC5lcSgnbm90aWZpY2FjaW9uZXNfYWN0aXZhcycsIHRydWUpCiAgICAuaW4oJ3VzZXJfaWQnLCBpZHNVc3VhcmlvcykKCiAgY29uc3QgY29uTm90aWYgPSBuZXcgU2V0KChhY3Rpdm9zIHx8IFtdKS5tYXAoYSA9PiBhLnVzZXJfaWQpKQogIGlmIChjb25Ob3RpZi5zaXplID09PSAwKSB7CiAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24oeyBtZW5zYWplOiAnTmFkaWUgY29uIG5vdGlmaWNhY2lvbmVzIGFjdGl2YXMnLCBmZWNoYTogbWFuaWFuYSwgZW52aWFkb3M6IDAgfSkKICB9CgogIC8vIFBhc28gMzogbm9tYnJlcyBkZSBsYXMgbWFzY290YXMgaW52b2x1Y3JhZGFzLgogIGNvbnN0IGlkc01hc2NvdGFzID0gQXJyYXkuZnJvbShuZXcgU2V0KHZpc2l0YXMubWFwKHYgPT4gdi5tYXNjb3RhX2lkKS5maWx0ZXIoQm9vbGVhbikpKQogIGNvbnN0IHsgZGF0YTogbWFzY290YXMgfSA9IGF3YWl0IHN1cGFiYXNlCiAgICAuZnJvbSgnbWFzY290YXMnKQogICAgLnNlbGVjdCgnaWQsIG5vbWJyZScpCiAgICAuaW4oJ2lkJywgaWRzTWFzY290YXMpCiAgY29uc3Qgbm9tYnJlUG9yTWFzY290YSA9IG5ldyBNYXAoKG1hc2NvdGFzIHx8IFtdKS5tYXAobSA9PiBbbS5pZCwgbS5ub21icmVdKSkKCiAgLy8gUGFzbyA0OiBzdXNjcmlwY2lvbmVzIHB1c2ggZGUgZXNvcyB1c3VhcmlvcyAoYWxndWllbiBwdWVkZSB0ZW5lcgogIC8vIG3DoXMgZGUgdW5hIHNpIGluc3RhbMOzIGxhIGFwcCBlbiB2YXJpb3MgZGlzcG9zaXRpdm9zKS4KICBjb25zdCB7IGRhdGE6IHN1YnMgfSA9IGF3YWl0IHN1cGFiYXNlCiAgICAuZnJvbSgnc3VzY3JpcGNpb25lc19wdXNoJykKICAgIC5zZWxlY3QoJ2lkLCB1c2VyX2lkLCBlbmRwb2ludCwgcDI1NmRoLCBhdXRoJykKICAgIC5pbigndXNlcl9pZCcsIEFycmF5LmZyb20oY29uTm90aWYpKQoKICBjb25zdCBzdWJzUG9yVXN1YXJpbyA9IG5ldyBNYXA8c3RyaW5nLCBhbnlbXT4oKQogIGZvciAoY29uc3QgcyBvZiAoc3VicyB8fCBbXSkpIHsKICAgIGNvbnN0IGFyciA9IHN1YnNQb3JVc3VhcmlvLmdldChzLnVzZXJfaWQpIHx8IFtdCiAgICBhcnIucHVzaChzKQogICAgc3Vic1BvclVzdWFyaW8uc2V0KHMudXNlcl9pZCwgYXJyKQogIH0KCiAgbGV0IHRvdGFsRW52aWFkb3MgPSAwCiAgbGV0IHRvdGFsRXJyb3JlcyA9IDAKCiAgZm9yIChjb25zdCB2IG9mIHZpc2l0YXMpIHsKICAgIGlmICghY29uTm90aWYuaGFzKHYudXNlcl9pZCkpIGNvbnRpbnVlCgogICAgY29uc3Qgc3VzY3JpcGNpb25lcyA9IHN1YnNQb3JVc3VhcmlvLmdldCh2LnVzZXJfaWQpIHx8IFtdCiAgICBpZiAoc3VzY3JpcGNpb25lcy5sZW5ndGggPT09IDApIGNvbnRpbnVlCgogICAgY29uc3Qgbm9tYnJlID0gbm9tYnJlUG9yTWFzY290YS5nZXQodi5tYXNjb3RhX2lkKSB8fCAndHUgbWFzY290YScKICAgIGNvbnN0IGhvcmEgPSB2LmhvcmEgPyBgIGEgbGFzICR7U3RyaW5nKHYuaG9yYSkuc2xpY2UoMCwgNSl9YCA6ICcnCiAgICBjb25zdCBxdWllbiA9IHYudmV0ZXJpbmFyaW8gPyBgIGNvbiAke3YudmV0ZXJpbmFyaW99YCA6ICcnCiAgICBjb25zdCBkZXRhbGxlID0gZGVzY3JpcGNpb25WaXNpdGEodi50aXBvLCB2Lm1vdGl2bykKCiAgICBjb25zdCBwYXlsb2FkID0gSlNPTi5zdHJpbmdpZnkoewogICAgICB0aXRsZTogJ0NISVFVSSBFbnRyZSBTZcOxYWxlcycsCiAgICAgIGJvZHk6IGDwn4+lIE1hw7FhbmEgJHtub21icmV9IHRpZW5lIGhvcmEke2hvcmF9JHtxdWllbn06ICR7ZGV0YWxsZX0uYCwKICAgICAgdXJsOiAnL3ByZXZlbmNpb24nLAogICAgfSkKCiAgICBmb3IgKGNvbnN0IHN1YiBvZiBzdXNjcmlwY2lvbmVzKSB7CiAgICAgIHRyeSB7CiAgICAgICAgYXdhaXQgd2VicHVzaC5zZW5kTm90aWZpY2F0aW9uKAogICAgICAgICAgeyBlbmRwb2ludDogc3ViLmVuZHBvaW50LCBrZXlzOiB7IHAyNTZkaDogc3ViLnAyNTZkaCwgYXV0aDogc3ViLmF1dGggfSB9LAogICAgICAgICAgcGF5bG9hZCwKICAgICAgICAgIHsgdXJnZW5jeTogJ2hpZ2gnIH0KICAgICAgICApCiAgICAgICAgdG90YWxFbnZpYWRvcysrCiAgICAgIH0gY2F0Y2ggKGVycjogYW55KSB7CiAgICAgICAgdG90YWxFcnJvcmVzKysKICAgICAgICAvLyBTdXNjcmlwY2nDs24gbXVlcnRhIChhcHAgZGVzaW5zdGFsYWRhIG8gcGVybWlzbyByZXZvY2Fkbyk6IHNlCiAgICAgICAgLy8gbGltcGlhIHBhcmEgbm8gc2VndWlyIGludGVudGFuZG8gZW4gdmFuby4KICAgICAgICBpZiAoZXJyLnN0YXR1c0NvZGUgPT09IDQwNCB8fCBlcnIuc3RhdHVzQ29kZSA9PT0gNDEwKSB7CiAgICAgICAgICBhd2FpdCBzdXBhYmFzZS5mcm9tKCdzdXNjcmlwY2lvbmVzX3B1c2gnKS5kZWxldGUoKS5lcSgnaWQnLCBzdWIuaWQpCiAgICAgICAgfQogICAgICB9CiAgICB9CiAgfQoKICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24oewogICAgaG9yYTogaG9yYUFjdHVhbCwKICAgIGZlY2hhOiBtYW5pYW5hLAogICAgdmlzaXRhczogdmlzaXRhcy5sZW5ndGgsCiAgICBlbnZpYWRvczogdG90YWxFbnZpYWRvcywKICAgIGVycm9yZXM6IHRvdGFsRXJyb3JlcywKICB9KQp9Cg==';

function abortar(motivo) {
  console.log('');
  console.log('ABORTADO: ' + motivo);
  console.log('No se modifico ningun archivo. Avisale a Claude lo que dice este mensaje.');
  process.exit(1);
}

const destino = path.join(process.cwd(), RUTA);

if (fs.existsSync(destino)) {
  abortar('ya existe ' + RUTA + '. No lo sobrescribo por si tiene cambios tuyos.');
}

// La ruta hermana tiene que existir: si no, no estamos en la raiz del
// proyecto o la estructura es distinta a la esperada.
if (!fs.existsSync(path.join(process.cwd(), 'app/api/cron/recordatorios/route.ts'))) {
  abortar('no se encontro app/api/cron/recordatorios/route.ts. Corre el script desde la raiz del proyecto.');
}
console.log('  OK la carpeta de crons es la esperada');

const contenido = Buffer.from(VISITAS_B64, 'base64').toString('utf8');

const REQUERIDOS = ['CRON_SECRET', 'HORA_ENVIO', 'visitas_veterinarias', 'notificaciones_activas', 'webpush.sendNotification'];
for (const r of REQUERIDOS) {
  if (!contenido.includes(r)) {
    abortar('el contenido no incluye [' + r + ']. Script corrupto, no se escribio nada.');
  }
}
console.log('  OK el contenido trae la proteccion y los filtros');

const carpeta = path.dirname(destino);
if (!fs.existsSync(carpeta)) {
  fs.mkdirSync(carpeta, { recursive: true });
}
fs.writeFileSync(destino, contenido, 'utf8');

console.log('');
console.log('OK: ' + RUTA);
console.log('');
console.log('FALTA UN PASO: agregar el job en cron-job.org apuntando a');
console.log('/api/cron/visitas, cada hora, con el mismo CRON_SECRET.');
