// Script: generar_78_manifest_fix.js
// Fix: quita 'label' y 'form_factor' de screenshots que el tipo
// MetadataRoute.Manifest de Next.js no acepta.

const fs = require('fs');
const path = require('path');

const filePath = path.join('app', 'manifest.ts');
const b64 = "aW1wb3J0IHR5cGUgeyBNZXRhZGF0YVJvdXRlIH0gZnJvbSAnbmV4dCcKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIG1hbmlmZXN0KCk6IE1ldGFkYXRhUm91dGUuTWFuaWZlc3QgewogIHJldHVybiB7CiAgICBpZDogJ2NsLmNoaXF1aS5lbnRyZXNlbmhhbGVzJywKICAgIG5hbWU6ICdDSElRVUkgRW50cmUgU2XDsWFsZXMnLAogICAgc2hvcnRfbmFtZTogJ0NISVFVSScsCiAgICBkZXNjcmlwdGlvbjogJ1R1IGNvbXBhw7Flcm8gZGUgb2JzZXJ2YWNpw7NuIHkgY3VpZGFkbyBwYXJhIGxhIHNhbHVkIGRlIHR1IG1hc2NvdGEuIFJlZ2lzdHJhIHPDrW50b21hcywgdmFjdW5hcywgcGFzZW9zIHkgbcOhcy4nLAogICAgc3RhcnRfdXJsOiAnL2Rhc2hib2FyZCcsCiAgICBzY29wZTogJy8nLAogICAgZGlzcGxheTogJ3N0YW5kYWxvbmUnLAogICAgYmFja2dyb3VuZF9jb2xvcjogJyNGNUVERTMnLAogICAgdGhlbWVfY29sb3I6ICcjOEM1NzJGJywKICAgIG9yaWVudGF0aW9uOiAncG9ydHJhaXQnLAogICAgY2F0ZWdvcmllczogWydoZWFsdGgnLCAnbGlmZXN0eWxlJywgJ3V0aWxpdGllcyddLAogICAgcHJlZmVyX3JlbGF0ZWRfYXBwbGljYXRpb25zOiBmYWxzZSwKICAgIGljb25zOiBbCiAgICAgIHsKICAgICAgICBzcmM6ICcvaWNvbi0xOTJ4MTkyLnBuZycsCiAgICAgICAgc2l6ZXM6ICcxOTJ4MTkyJywKICAgICAgICB0eXBlOiAnaW1hZ2UvcG5nJywKICAgICAgICBwdXJwb3NlOiAnYW55JywKICAgICAgfSwKICAgICAgewogICAgICAgIHNyYzogJy9pY29uLTUxMng1MTIucG5nJywKICAgICAgICBzaXplczogJzUxMng1MTInLAogICAgICAgIHR5cGU6ICdpbWFnZS9wbmcnLAogICAgICAgIHB1cnBvc2U6ICdhbnknLAogICAgICB9LAogICAgICB7CiAgICAgICAgc3JjOiAnL2ljb24tbWFza2FibGUtNTEyeDUxMi5wbmcnLAogICAgICAgIHNpemVzOiAnNTEyeDUxMicsCiAgICAgICAgdHlwZTogJ2ltYWdlL3BuZycsCiAgICAgICAgcHVycG9zZTogJ21hc2thYmxlJywKICAgICAgfSwKICAgIF0sCiAgICBzY3JlZW5zaG90czogWwogICAgICB7CiAgICAgICAgc3JjOiAnL3NjcmVlbnNob3RzL2Rhc2hib2FyZC5wbmcnLAogICAgICAgIHNpemVzOiAnMTA4MHgxOTIwJywKICAgICAgICB0eXBlOiAnaW1hZ2UvcG5nJywKICAgICAgfSwKICAgICAgewogICAgICAgIHNyYzogJy9zY3JlZW5zaG90cy9yZWdpc3Ryby5wbmcnLAogICAgICAgIHNpemVzOiAnMTA4MHgxOTIwJywKICAgICAgICB0eXBlOiAnaW1hZ2UvcG5nJywKICAgICAgfSwKICAgICAgewogICAgICAgIHNyYzogJy9zY3JlZW5zaG90cy9wcmV2ZW5jaW9uLnBuZycsCiAgICAgICAgc2l6ZXM6ICcxMDgweDE5MjAnLAogICAgICAgIHR5cGU6ICdpbWFnZS9wbmcnLAogICAgICB9LAogICAgXSwKICB9Cn0K";
const content = Buffer.from(b64, 'base64').toString('utf8');
const dir = path.dirname(filePath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(filePath, content, 'utf8');
console.log('OK: ' + filePath);
